// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: danmaku/danmaku_service.proto

package danmaku

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_danmaku_danmaku_service_proto protoreflect.FileDescriptor

const file_danmaku_danmaku_service_proto_rawDesc = "" +
	"\n" +
	"\x1ddanmaku/danmaku_service.proto\x12\adanmaku\x1a\x19danmaku/danmaku_api.proto2\xb5\x01\n" +
	"\x0eDanmakuService\x12H\n" +
	"\vSendDanmaku\x12\x1b.danmaku.SendDanmakuRequest\x1a\x1c.danmaku.SendDanmakuResponse\x12Y\n" +
	"\x10SubscribeDanmaku\x12 .danmaku.SubscribeDanmakuRequest\x1a!.danmaku.SubscribeDanmakuResponse0\x01B\x1eZ\x1cshared/proto/danmaku;danmakub\x06proto3"

var file_danmaku_danmaku_service_proto_goTypes = []any{
	(*SendDanmakuRequest)(nil),       // 0: danmaku.SendDanmakuRequest
	(*SubscribeDanmakuRequest)(nil),  // 1: danmaku.SubscribeDanmakuRequest
	(*SendDanmakuResponse)(nil),      // 2: danmaku.SendDanmakuResponse
	(*SubscribeDanmakuResponse)(nil), // 3: danmaku.SubscribeDanmakuResponse
}
var file_danmaku_danmaku_service_proto_depIdxs = []int32{
	0, // 0: danmaku.DanmakuService.SendDanmaku:input_type -> danmaku.SendDanmakuRequest
	1, // 1: danmaku.DanmakuService.SubscribeDanmaku:input_type -> danmaku.SubscribeDanmakuRequest
	2, // 2: danmaku.DanmakuService.SendDanmaku:output_type -> danmaku.SendDanmakuResponse
	3, // 3: danmaku.DanmakuService.SubscribeDanmaku:output_type -> danmaku.SubscribeDanmakuResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_danmaku_danmaku_service_proto_init() }
func file_danmaku_danmaku_service_proto_init() {
	if File_danmaku_danmaku_service_proto != nil {
		return
	}
	file_danmaku_danmaku_api_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_danmaku_danmaku_service_proto_rawDesc), len(file_danmaku_danmaku_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_danmaku_danmaku_service_proto_goTypes,
		DependencyIndexes: file_danmaku_danmaku_service_proto_depIdxs,
	}.Build()
	File_danmaku_danmaku_service_proto = out.File
	file_danmaku_danmaku_service_proto_goTypes = nil
	file_danmaku_danmaku_service_proto_depIdxs = nil
}
