// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: danmaku/danmaku.proto

package danmaku

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Danmaku struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomId          string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId          string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username        string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Content         string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Type            DanmakuType            `protobuf:"varint,6,opt,name=type,proto3,enum=danmaku.DanmakuType" json:"type,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	MentionedUserId string                 `protobuf:"bytes,8,opt,name=mentioned_user_id,json=mentionedUserId,proto3" json:"mentioned_user_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Danmaku) Reset() {
	*x = Danmaku{}
	mi := &file_danmaku_danmaku_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Danmaku) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Danmaku) ProtoMessage() {}

func (x *Danmaku) ProtoReflect() protoreflect.Message {
	mi := &file_danmaku_danmaku_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Danmaku.ProtoReflect.Descriptor instead.
func (*Danmaku) Descriptor() ([]byte, []int) {
	return file_danmaku_danmaku_proto_rawDescGZIP(), []int{0}
}

func (x *Danmaku) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Danmaku) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Danmaku) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Danmaku) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Danmaku) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Danmaku) GetType() DanmakuType {
	if x != nil {
		return x.Type
	}
	return DanmakuType_DANMAKU_TYPE_NORMAL
}

func (x *Danmaku) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Danmaku) GetMentionedUserId() string {
	if x != nil {
		return x.MentionedUserId
	}
	return ""
}

// 房间实体
type Room struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HostId        string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"` // 主播id
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	State         RoomState              `protobuf:"varint,4,opt,name=state,proto3,enum=danmaku.RoomState" json:"state,omitempty"`
	ViewerCount   int32                  `protobuf:"varint,5,opt,name=viewer_count,json=viewerCount,proto3" json:"viewer_count,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	BlockedUsers  []string               `protobuf:"bytes,7,rep,name=blocked_users,json=blockedUsers,proto3" json:"blocked_users,omitempty"` // 禁言用户
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_danmaku_danmaku_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_danmaku_danmaku_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_danmaku_danmaku_proto_rawDescGZIP(), []int{1}
}

func (x *Room) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Room) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *Room) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Room) GetState() RoomState {
	if x != nil {
		return x.State
	}
	return RoomState_ROOM_STATE_UNSPECIFIED
}

func (x *Room) GetViewerCount() int32 {
	if x != nil {
		return x.ViewerCount
	}
	return 0
}

func (x *Room) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Room) GetBlockedUsers() []string {
	if x != nil {
		return x.BlockedUsers
	}
	return nil
}

var File_danmaku_danmaku_proto protoreflect.FileDescriptor

const file_danmaku_danmaku_proto_rawDesc = "" +
	"\n" +
	"\x15danmaku/danmaku.proto\x12\adanmaku\x1a\x13danmaku/types.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x92\x02\n" +
	"\aDanmaku\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12(\n" +
	"\x04type\x18\x06 \x01(\x0e2\x14.danmaku.DanmakuTypeR\x04type\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12*\n" +
	"\x11mentioned_user_id\x18\b \x01(\tR\x0fmentionedUserId\"\xf2\x01\n" +
	"\x04Room\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12(\n" +
	"\x05state\x18\x04 \x01(\x0e2\x12.danmaku.RoomStateR\x05state\x12!\n" +
	"\fviewer_count\x18\x05 \x01(\x05R\vviewerCount\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12#\n" +
	"\rblocked_users\x18\a \x03(\tR\fblockedUsersB\x1eZ\x1cshared/proto/danmaku;danmakub\x06proto3"

var (
	file_danmaku_danmaku_proto_rawDescOnce sync.Once
	file_danmaku_danmaku_proto_rawDescData []byte
)

func file_danmaku_danmaku_proto_rawDescGZIP() []byte {
	file_danmaku_danmaku_proto_rawDescOnce.Do(func() {
		file_danmaku_danmaku_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_danmaku_danmaku_proto_rawDesc), len(file_danmaku_danmaku_proto_rawDesc)))
	})
	return file_danmaku_danmaku_proto_rawDescData
}

var file_danmaku_danmaku_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_danmaku_danmaku_proto_goTypes = []any{
	(*Danmaku)(nil),               // 0: danmaku.Danmaku
	(*Room)(nil),                  // 1: danmaku.Room
	(DanmakuType)(0),              // 2: danmaku.DanmakuType
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(RoomState)(0),                // 4: danmaku.RoomState
}
var file_danmaku_danmaku_proto_depIdxs = []int32{
	2, // 0: danmaku.Danmaku.type:type_name -> danmaku.DanmakuType
	3, // 1: danmaku.Danmaku.created_at:type_name -> google.protobuf.Timestamp
	4, // 2: danmaku.Room.state:type_name -> danmaku.RoomState
	3, // 3: danmaku.Room.created_at:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_danmaku_danmaku_proto_init() }
func file_danmaku_danmaku_proto_init() {
	if File_danmaku_danmaku_proto != nil {
		return
	}
	file_danmaku_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_danmaku_danmaku_proto_rawDesc), len(file_danmaku_danmaku_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_danmaku_danmaku_proto_goTypes,
		DependencyIndexes: file_danmaku_danmaku_proto_depIdxs,
		MessageInfos:      file_danmaku_danmaku_proto_msgTypes,
	}.Build()
	File_danmaku_danmaku_proto = out.File
	file_danmaku_danmaku_proto_goTypes = nil
	file_danmaku_danmaku_proto_depIdxs = nil
}
