// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Mute is the predicate function for mute builders.
type Mute func(*sql.Selector)

// Room is the predicate function for room builders.
type Room func(*sql.Selector)

// UserRoomRole is the predicate function for userroomrole builders.
type UserRoomRole func(*sql.Selector)
