// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: gift/gift.proto

package gift

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GiftStatus int32

const (
	GiftStatus_GIFT_STATUS_UNSPECIFIED  GiftStatus = 0 // 未指定
	GiftStatus_GIFT_STATUS_ONLINE       GiftStatus = 1 // 上线
	GiftStatus_GIFT_STATUS_OFFLINE      GiftStatus = 2 // 下线
	GiftStatus_GIFT_STATUS_LIMITED_TIME GiftStatus = 3 // 限时
)

// Enum value maps for GiftStatus.
var (
	GiftStatus_name = map[int32]string{
		0: "GIFT_STATUS_UNSPECIFIED",
		1: "GIFT_STATUS_ONLINE",
		2: "GIFT_STATUS_OFFLINE",
		3: "GIFT_STATUS_LIMITED_TIME",
	}
	GiftStatus_value = map[string]int32{
		"GIFT_STATUS_UNSPECIFIED":  0,
		"GIFT_STATUS_ONLINE":       1,
		"GIFT_STATUS_OFFLINE":      2,
		"GIFT_STATUS_LIMITED_TIME": 3,
	}
)

func (x GiftStatus) Enum() *GiftStatus {
	p := new(GiftStatus)
	*p = x
	return p
}

func (x GiftStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GiftStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_gift_gift_proto_enumTypes[0].Descriptor()
}

func (GiftStatus) Type() protoreflect.EnumType {
	return &file_gift_gift_proto_enumTypes[0]
}

func (x GiftStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GiftStatus.Descriptor instead.
func (GiftStatus) EnumDescriptor() ([]byte, []int) {
	return file_gift_gift_proto_rawDescGZIP(), []int{0}
}

type GiftRecordStatus int32

const (
	GiftRecordStatus_GIFT_RECORD_STATUS_UNSPECIFIED GiftRecordStatus = 0 // 未指定
	GiftRecordStatus_GIFT_RECORD_STATUS_PENDING     GiftRecordStatus = 1 // 处理中
	GiftRecordStatus_GIFT_RECORD_STATUS_SUCCESS     GiftRecordStatus = 2 // 成功
	GiftRecordStatus_GIFT_RECORD_STATUS_FAILED      GiftRecordStatus = 3 // 失败
)

// Enum value maps for GiftRecordStatus.
var (
	GiftRecordStatus_name = map[int32]string{
		0: "GIFT_RECORD_STATUS_UNSPECIFIED",
		1: "GIFT_RECORD_STATUS_PENDING",
		2: "GIFT_RECORD_STATUS_SUCCESS",
		3: "GIFT_RECORD_STATUS_FAILED",
	}
	GiftRecordStatus_value = map[string]int32{
		"GIFT_RECORD_STATUS_UNSPECIFIED": 0,
		"GIFT_RECORD_STATUS_PENDING":     1,
		"GIFT_RECORD_STATUS_SUCCESS":     2,
		"GIFT_RECORD_STATUS_FAILED":      3,
	}
)

func (x GiftRecordStatus) Enum() *GiftRecordStatus {
	p := new(GiftRecordStatus)
	*p = x
	return p
}

func (x GiftRecordStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GiftRecordStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_gift_gift_proto_enumTypes[1].Descriptor()
}

func (GiftRecordStatus) Type() protoreflect.EnumType {
	return &file_gift_gift_proto_enumTypes[1]
}

func (x GiftRecordStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GiftRecordStatus.Descriptor instead.
func (GiftRecordStatus) EnumDescriptor() ([]byte, []int) {
	return file_gift_gift_proto_rawDescGZIP(), []int{1}
}

type Gift struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	IconUrl       string                 `protobuf:"bytes,4,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	CacheKey      string                 `protobuf:"bytes,5,opt,name=cache_key,json=cacheKey,proto3" json:"cache_key,omitempty"`
	Price         int64                  `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	VipOnly       bool                   `protobuf:"varint,7,opt,name=vip_only,json=vipOnly,proto3" json:"vip_only,omitempty"`
	Status        GiftStatus             `protobuf:"varint,9,opt,name=status,proto3,enum=gift.GiftStatus" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gift) Reset() {
	*x = Gift{}
	mi := &file_gift_gift_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gift) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gift) ProtoMessage() {}

func (x *Gift) ProtoReflect() protoreflect.Message {
	mi := &file_gift_gift_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gift.ProtoReflect.Descriptor instead.
func (*Gift) Descriptor() ([]byte, []int) {
	return file_gift_gift_proto_rawDescGZIP(), []int{0}
}

func (x *Gift) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Gift) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Gift) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Gift) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *Gift) GetCacheKey() string {
	if x != nil {
		return x.CacheKey
	}
	return ""
}

func (x *Gift) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Gift) GetVipOnly() bool {
	if x != nil {
		return x.VipOnly
	}
	return false
}

func (x *Gift) GetStatus() GiftStatus {
	if x != nil {
		return x.Status
	}
	return GiftStatus_GIFT_STATUS_UNSPECIFIED
}

func (x *Gift) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Gift) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type Wallet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // UUID
	Balance       int64                  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	VersionNumber int64                  `protobuf:"varint,3,opt,name=version_number,json=versionNumber,proto3" json:"version_number,omitempty"` // 乐观锁版本号
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wallet) Reset() {
	*x = Wallet{}
	mi := &file_gift_gift_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wallet) ProtoMessage() {}

func (x *Wallet) ProtoReflect() protoreflect.Message {
	mi := &file_gift_gift_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wallet.ProtoReflect.Descriptor instead.
func (*Wallet) Descriptor() ([]byte, []int) {
	return file_gift_gift_proto_rawDescGZIP(), []int{1}
}

func (x *Wallet) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Wallet) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *Wallet) GetVersionNumber() int64 {
	if x != nil {
		return x.VersionNumber
	}
	return 0
}

func (x *Wallet) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Wallet) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type GiftRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"` // UUID，作为幂等性防重的主键
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                         // UUID
	AnchorId       string                 `protobuf:"bytes,3,opt,name=anchor_id,json=anchorId,proto3" json:"anchor_id,omitempty"`                   // UUID
	RoomId         string                 `protobuf:"bytes,4,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                         // UUID
	GiftId         string                 `protobuf:"bytes,5,opt,name=gift_id,json=giftId,proto3" json:"gift_id,omitempty"`                         // UUID
	Amount         int64                  `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Status         GiftRecordStatus       `protobuf:"varint,7,opt,name=status,proto3,enum=gift.GiftRecordStatus" json:"status,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GiftRecord) Reset() {
	*x = GiftRecord{}
	mi := &file_gift_gift_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GiftRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiftRecord) ProtoMessage() {}

func (x *GiftRecord) ProtoReflect() protoreflect.Message {
	mi := &file_gift_gift_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiftRecord.ProtoReflect.Descriptor instead.
func (*GiftRecord) Descriptor() ([]byte, []int) {
	return file_gift_gift_proto_rawDescGZIP(), []int{2}
}

func (x *GiftRecord) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *GiftRecord) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GiftRecord) GetAnchorId() string {
	if x != nil {
		return x.AnchorId
	}
	return ""
}

func (x *GiftRecord) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GiftRecord) GetGiftId() string {
	if x != nil {
		return x.GiftId
	}
	return ""
}

func (x *GiftRecord) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *GiftRecord) GetStatus() GiftRecordStatus {
	if x != nil {
		return x.Status
	}
	return GiftRecordStatus_GIFT_RECORD_STATUS_UNSPECIFIED
}

func (x *GiftRecord) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GiftRecord) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type LeaderboardEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // UUID
	Score         int64                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`                // 累计送礼金额
	Rank          int32                  `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardEntry) Reset() {
	*x = LeaderboardEntry{}
	mi := &file_gift_gift_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardEntry) ProtoMessage() {}

func (x *LeaderboardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_gift_gift_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardEntry.ProtoReflect.Descriptor instead.
func (*LeaderboardEntry) Descriptor() ([]byte, []int) {
	return file_gift_gift_proto_rawDescGZIP(), []int{3}
}

func (x *LeaderboardEntry) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LeaderboardEntry) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *LeaderboardEntry) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

var File_gift_gift_proto protoreflect.FileDescriptor

const file_gift_gift_proto_rawDesc = "" +
	"\n" +
	"\x0fgift/gift.proto\x12\x04gift\"\x9d\x02\n" +
	"\x04Gift\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\bicon_url\x18\x04 \x01(\tR\aiconUrl\x12\x1b\n" +
	"\tcache_key\x18\x05 \x01(\tR\bcacheKey\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x03R\x05price\x12\x19\n" +
	"\bvip_only\x18\a \x01(\bR\avipOnly\x12(\n" +
	"\x06status\x18\t \x01(\x0e2\x10.gift.GiftStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\x03R\tupdatedAt\"\xa0\x01\n" +
	"\x06Wallet\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x03R\abalance\x12%\n" +
	"\x0eversion_number\x18\x03 \x01(\x03R\rversionNumber\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt\"\xa3\x02\n" +
	"\n" +
	"GiftRecord\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tanchor_id\x18\x03 \x01(\tR\banchorId\x12\x17\n" +
	"\aroom_id\x18\x04 \x01(\tR\x06roomId\x12\x17\n" +
	"\agift_id\x18\x05 \x01(\tR\x06giftId\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x03R\x06amount\x12.\n" +
	"\x06status\x18\a \x01(\x0e2\x16.gift.GiftRecordStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt\"U\n" +
	"\x10LeaderboardEntry\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x03R\x05score\x12\x12\n" +
	"\x04rank\x18\x03 \x01(\x05R\x04rank*x\n" +
	"\n" +
	"GiftStatus\x12\x1b\n" +
	"\x17GIFT_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12GIFT_STATUS_ONLINE\x10\x01\x12\x17\n" +
	"\x13GIFT_STATUS_OFFLINE\x10\x02\x12\x1c\n" +
	"\x18GIFT_STATUS_LIMITED_TIME\x10\x03*\x95\x01\n" +
	"\x10GiftRecordStatus\x12\"\n" +
	"\x1eGIFT_RECORD_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aGIFT_RECORD_STATUS_PENDING\x10\x01\x12\x1e\n" +
	"\x1aGIFT_RECORD_STATUS_SUCCESS\x10\x02\x12\x1d\n" +
	"\x19GIFT_RECORD_STATUS_FAILED\x10\x03B\x18Z\x16shared/proto/gift;giftb\x06proto3"

var (
	file_gift_gift_proto_rawDescOnce sync.Once
	file_gift_gift_proto_rawDescData []byte
)

func file_gift_gift_proto_rawDescGZIP() []byte {
	file_gift_gift_proto_rawDescOnce.Do(func() {
		file_gift_gift_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gift_gift_proto_rawDesc), len(file_gift_gift_proto_rawDesc)))
	})
	return file_gift_gift_proto_rawDescData
}

var file_gift_gift_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_gift_gift_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gift_gift_proto_goTypes = []any{
	(GiftStatus)(0),          // 0: gift.GiftStatus
	(GiftRecordStatus)(0),    // 1: gift.GiftRecordStatus
	(*Gift)(nil),             // 2: gift.Gift
	(*Wallet)(nil),           // 3: gift.Wallet
	(*GiftRecord)(nil),       // 4: gift.GiftRecord
	(*LeaderboardEntry)(nil), // 5: gift.LeaderboardEntry
}
var file_gift_gift_proto_depIdxs = []int32{
	0, // 0: gift.Gift.status:type_name -> gift.GiftStatus
	1, // 1: gift.GiftRecord.status:type_name -> gift.GiftRecordStatus
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gift_gift_proto_init() }
func file_gift_gift_proto_init() {
	if File_gift_gift_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gift_gift_proto_rawDesc), len(file_gift_gift_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gift_gift_proto_goTypes,
		DependencyIndexes: file_gift_gift_proto_depIdxs,
		EnumInfos:         file_gift_gift_proto_enumTypes,
		MessageInfos:      file_gift_gift_proto_msgTypes,
	}.Build()
	File_gift_gift_proto = out.File
	file_gift_gift_proto_goTypes = nil
	file_gift_gift_proto_depIdxs = nil
}
