// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: gift/gift_api.proto

package gift

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendGiftRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"` // UUID，用于防重和幂等性
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                         // UUID
	AnchorId       string                 `protobuf:"bytes,3,opt,name=anchor_id,json=anchorId,proto3" json:"anchor_id,omitempty"`                   // UUID
	RoomId         string                 `protobuf:"bytes,4,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                         // UUID
	GiftId         string                 `protobuf:"bytes,5,opt,name=gift_id,json=giftId,proto3" json:"gift_id,omitempty"`                         // UUID
	Amount         int64                  `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendGiftRequest) Reset() {
	*x = SendGiftRequest{}
	mi := &file_gift_gift_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendGiftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGiftRequest) ProtoMessage() {}

func (x *SendGiftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gift_gift_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGiftRequest.ProtoReflect.Descriptor instead.
func (*SendGiftRequest) Descriptor() ([]byte, []int) {
	return file_gift_gift_api_proto_rawDescGZIP(), []int{0}
}

func (x *SendGiftRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *SendGiftRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendGiftRequest) GetAnchorId() string {
	if x != nil {
		return x.AnchorId
	}
	return ""
}

func (x *SendGiftRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SendGiftRequest) GetGiftId() string {
	if x != nil {
		return x.GiftId
	}
	return ""
}

func (x *SendGiftRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type SendGiftResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Balance       int64                  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendGiftResponse) Reset() {
	*x = SendGiftResponse{}
	mi := &file_gift_gift_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendGiftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGiftResponse) ProtoMessage() {}

func (x *SendGiftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gift_gift_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGiftResponse.ProtoReflect.Descriptor instead.
func (*SendGiftResponse) Descriptor() ([]byte, []int) {
	return file_gift_gift_api_proto_rawDescGZIP(), []int{1}
}

func (x *SendGiftResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendGiftResponse) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type GetWalletBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletBalanceRequest) Reset() {
	*x = GetWalletBalanceRequest{}
	mi := &file_gift_gift_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletBalanceRequest) ProtoMessage() {}

func (x *GetWalletBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gift_gift_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetWalletBalanceRequest) Descriptor() ([]byte, []int) {
	return file_gift_gift_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetWalletBalanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetWalletBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallet        *Wallet                `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletBalanceResponse) Reset() {
	*x = GetWalletBalanceResponse{}
	mi := &file_gift_gift_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletBalanceResponse) ProtoMessage() {}

func (x *GetWalletBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gift_gift_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetWalletBalanceResponse) Descriptor() ([]byte, []int) {
	return file_gift_gift_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetWalletBalanceResponse) GetWallet() *Wallet {
	if x != nil {
		return x.Wallet
	}
	return nil
}

type ListGiftsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGiftsRequest) Reset() {
	*x = ListGiftsRequest{}
	mi := &file_gift_gift_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGiftsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGiftsRequest) ProtoMessage() {}

func (x *ListGiftsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gift_gift_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGiftsRequest.ProtoReflect.Descriptor instead.
func (*ListGiftsRequest) Descriptor() ([]byte, []int) {
	return file_gift_gift_api_proto_rawDescGZIP(), []int{4}
}

type ListGiftsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gifts         []*Gift                `protobuf:"bytes,1,rep,name=gifts,proto3" json:"gifts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGiftsResponse) Reset() {
	*x = ListGiftsResponse{}
	mi := &file_gift_gift_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGiftsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGiftsResponse) ProtoMessage() {}

func (x *ListGiftsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gift_gift_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGiftsResponse.ProtoReflect.Descriptor instead.
func (*ListGiftsResponse) Descriptor() ([]byte, []int) {
	return file_gift_gift_api_proto_rawDescGZIP(), []int{5}
}

func (x *ListGiftsResponse) GetGifts() []*Gift {
	if x != nil {
		return x.Gifts
	}
	return nil
}

type GetLeaderboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // UUID
	TopN          int32                  `protobuf:"varint,2,opt,name=top_n,json=topN,proto3" json:"top_n,omitempty"`      // 返回 Top N，默认 100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardRequest) Reset() {
	*x = GetLeaderboardRequest{}
	mi := &file_gift_gift_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardRequest) ProtoMessage() {}

func (x *GetLeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gift_gift_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardRequest.ProtoReflect.Descriptor instead.
func (*GetLeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_gift_gift_api_proto_rawDescGZIP(), []int{6}
}

func (x *GetLeaderboardRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GetLeaderboardRequest) GetTopN() int32 {
	if x != nil {
		return x.TopN
	}
	return 0
}

type GetLeaderboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LeaderboardEntry    `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardResponse) Reset() {
	*x = GetLeaderboardResponse{}
	mi := &file_gift_gift_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardResponse) ProtoMessage() {}

func (x *GetLeaderboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gift_gift_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardResponse.ProtoReflect.Descriptor instead.
func (*GetLeaderboardResponse) Descriptor() ([]byte, []int) {
	return file_gift_gift_api_proto_rawDescGZIP(), []int{7}
}

func (x *GetLeaderboardResponse) GetEntries() []*LeaderboardEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *GetLeaderboardResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type GetGiftRecordRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"` // UUID
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetGiftRecordRequest) Reset() {
	*x = GetGiftRecordRequest{}
	mi := &file_gift_gift_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGiftRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGiftRecordRequest) ProtoMessage() {}

func (x *GetGiftRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gift_gift_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGiftRecordRequest.ProtoReflect.Descriptor instead.
func (*GetGiftRecordRequest) Descriptor() ([]byte, []int) {
	return file_gift_gift_api_proto_rawDescGZIP(), []int{8}
}

func (x *GetGiftRecordRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type GetGiftRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GiftRecord    *GiftRecord            `protobuf:"bytes,1,opt,name=gift_record,json=giftRecord,proto3" json:"gift_record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGiftRecordResponse) Reset() {
	*x = GetGiftRecordResponse{}
	mi := &file_gift_gift_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGiftRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGiftRecordResponse) ProtoMessage() {}

func (x *GetGiftRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gift_gift_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGiftRecordResponse.ProtoReflect.Descriptor instead.
func (*GetGiftRecordResponse) Descriptor() ([]byte, []int) {
	return file_gift_gift_api_proto_rawDescGZIP(), []int{9}
}

func (x *GetGiftRecordResponse) GetGiftRecord() *GiftRecord {
	if x != nil {
		return x.GiftRecord
	}
	return nil
}

type ListGiftRecordsByRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // UUID
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGiftRecordsByRoomRequest) Reset() {
	*x = ListGiftRecordsByRoomRequest{}
	mi := &file_gift_gift_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGiftRecordsByRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGiftRecordsByRoomRequest) ProtoMessage() {}

func (x *ListGiftRecordsByRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gift_gift_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGiftRecordsByRoomRequest.ProtoReflect.Descriptor instead.
func (*ListGiftRecordsByRoomRequest) Descriptor() ([]byte, []int) {
	return file_gift_gift_api_proto_rawDescGZIP(), []int{10}
}

func (x *ListGiftRecordsByRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ListGiftRecordsByRoomRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListGiftRecordsByRoomRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListGiftRecordsByRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GiftRecords   []*GiftRecord          `protobuf:"bytes,1,rep,name=gift_records,json=giftRecords,proto3" json:"gift_records,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGiftRecordsByRoomResponse) Reset() {
	*x = ListGiftRecordsByRoomResponse{}
	mi := &file_gift_gift_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGiftRecordsByRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGiftRecordsByRoomResponse) ProtoMessage() {}

func (x *ListGiftRecordsByRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gift_gift_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGiftRecordsByRoomResponse.ProtoReflect.Descriptor instead.
func (*ListGiftRecordsByRoomResponse) Descriptor() ([]byte, []int) {
	return file_gift_gift_api_proto_rawDescGZIP(), []int{11}
}

func (x *ListGiftRecordsByRoomResponse) GetGiftRecords() []*GiftRecord {
	if x != nil {
		return x.GiftRecords
	}
	return nil
}

func (x *ListGiftRecordsByRoomResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_gift_gift_api_proto protoreflect.FileDescriptor

const file_gift_gift_api_proto_rawDesc = "" +
	"\n" +
	"\x13gift/gift_api.proto\x12\x04gift\x1a\x0fgift/gift.proto\"\xba\x01\n" +
	"\x0fSendGiftRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tanchor_id\x18\x03 \x01(\tR\banchorId\x12\x17\n" +
	"\aroom_id\x18\x04 \x01(\tR\x06roomId\x12\x17\n" +
	"\agift_id\x18\x05 \x01(\tR\x06giftId\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x03R\x06amount\"E\n" +
	"\x10SendGiftResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x03R\abalance\"2\n" +
	"\x17GetWalletBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"@\n" +
	"\x18GetWalletBalanceResponse\x12$\n" +
	"\x06wallet\x18\x01 \x01(\v2\f.gift.WalletR\x06wallet\"\x12\n" +
	"\x10ListGiftsRequest\"5\n" +
	"\x11ListGiftsResponse\x12 \n" +
	"\x05gifts\x18\x01 \x03(\v2\n" +
	".gift.GiftR\x05gifts\"E\n" +
	"\x15GetLeaderboardRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x13\n" +
	"\x05top_n\x18\x02 \x01(\x05R\x04topN\"c\n" +
	"\x16GetLeaderboardResponse\x120\n" +
	"\aentries\x18\x01 \x03(\v2\x16.gift.LeaderboardEntryR\aentries\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\"?\n" +
	"\x14GetGiftRecordRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\"J\n" +
	"\x15GetGiftRecordResponse\x121\n" +
	"\vgift_record\x18\x01 \x01(\v2\x10.gift.GiftRecordR\n" +
	"giftRecord\"e\n" +
	"\x1cListGiftRecordsByRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"j\n" +
	"\x1dListGiftRecordsByRoomResponse\x123\n" +
	"\fgift_records\x18\x01 \x03(\v2\x10.gift.GiftRecordR\vgiftRecords\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05totalB\x18Z\x16shared/proto/gift;giftb\x06proto3"

var (
	file_gift_gift_api_proto_rawDescOnce sync.Once
	file_gift_gift_api_proto_rawDescData []byte
)

func file_gift_gift_api_proto_rawDescGZIP() []byte {
	file_gift_gift_api_proto_rawDescOnce.Do(func() {
		file_gift_gift_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gift_gift_api_proto_rawDesc), len(file_gift_gift_api_proto_rawDesc)))
	})
	return file_gift_gift_api_proto_rawDescData
}

var file_gift_gift_api_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_gift_gift_api_proto_goTypes = []any{
	(*SendGiftRequest)(nil),               // 0: gift.SendGiftRequest
	(*SendGiftResponse)(nil),              // 1: gift.SendGiftResponse
	(*GetWalletBalanceRequest)(nil),       // 2: gift.GetWalletBalanceRequest
	(*GetWalletBalanceResponse)(nil),      // 3: gift.GetWalletBalanceResponse
	(*ListGiftsRequest)(nil),              // 4: gift.ListGiftsRequest
	(*ListGiftsResponse)(nil),             // 5: gift.ListGiftsResponse
	(*GetLeaderboardRequest)(nil),         // 6: gift.GetLeaderboardRequest
	(*GetLeaderboardResponse)(nil),        // 7: gift.GetLeaderboardResponse
	(*GetGiftRecordRequest)(nil),          // 8: gift.GetGiftRecordRequest
	(*GetGiftRecordResponse)(nil),         // 9: gift.GetGiftRecordResponse
	(*ListGiftRecordsByRoomRequest)(nil),  // 10: gift.ListGiftRecordsByRoomRequest
	(*ListGiftRecordsByRoomResponse)(nil), // 11: gift.ListGiftRecordsByRoomResponse
	(*Wallet)(nil),                        // 12: gift.Wallet
	(*Gift)(nil),                          // 13: gift.Gift
	(*LeaderboardEntry)(nil),              // 14: gift.LeaderboardEntry
	(*GiftRecord)(nil),                    // 15: gift.GiftRecord
}
var file_gift_gift_api_proto_depIdxs = []int32{
	12, // 0: gift.GetWalletBalanceResponse.wallet:type_name -> gift.Wallet
	13, // 1: gift.ListGiftsResponse.gifts:type_name -> gift.Gift
	14, // 2: gift.GetLeaderboardResponse.entries:type_name -> gift.LeaderboardEntry
	15, // 3: gift.GetGiftRecordResponse.gift_record:type_name -> gift.GiftRecord
	15, // 4: gift.ListGiftRecordsByRoomResponse.gift_records:type_name -> gift.GiftRecord
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_gift_gift_api_proto_init() }
func file_gift_gift_api_proto_init() {
	if File_gift_gift_api_proto != nil {
		return
	}
	file_gift_gift_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gift_gift_api_proto_rawDesc), len(file_gift_gift_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gift_gift_api_proto_goTypes,
		DependencyIndexes: file_gift_gift_api_proto_depIdxs,
		MessageInfos:      file_gift_gift_api_proto_msgTypes,
	}.Build()
	File_gift_gift_api_proto = out.File
	file_gift_gift_api_proto_goTypes = nil
	file_gift_gift_api_proto_depIdxs = nil
}
