// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: gift/gift_service.proto

package gift

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GiftService_SendGift_FullMethodName  = "/gift.GiftService/SendGift"
	GiftService_ListGifts_FullMethodName = "/gift.GiftService/ListGifts"
)

// GiftServiceClient is the client API for GiftService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GiftServiceClient interface {
	// 发送礼物（核心流程）- 返回幂等性防重
	SendGift(ctx context.Context, in *SendGiftRequest, opts ...grpc.CallOption) (*SendGiftResponse, error)
	// 获取全量礼物列表
	ListGifts(ctx context.Context, in *ListGiftsRequest, opts ...grpc.CallOption) (*ListGiftsResponse, error)
}

type giftServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGiftServiceClient(cc grpc.ClientConnInterface) GiftServiceClient {
	return &giftServiceClient{cc}
}

func (c *giftServiceClient) SendGift(ctx context.Context, in *SendGiftRequest, opts ...grpc.CallOption) (*SendGiftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendGiftResponse)
	err := c.cc.Invoke(ctx, GiftService_SendGift_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *giftServiceClient) ListGifts(ctx context.Context, in *ListGiftsRequest, opts ...grpc.CallOption) (*ListGiftsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGiftsResponse)
	err := c.cc.Invoke(ctx, GiftService_ListGifts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GiftServiceServer is the server API for GiftService service.
// All implementations must embed UnimplementedGiftServiceServer
// for forward compatibility.
type GiftServiceServer interface {
	// 发送礼物（核心流程）- 返回幂等性防重
	SendGift(context.Context, *SendGiftRequest) (*SendGiftResponse, error)
	// 获取全量礼物列表
	ListGifts(context.Context, *ListGiftsRequest) (*ListGiftsResponse, error)
	mustEmbedUnimplementedGiftServiceServer()
}

// UnimplementedGiftServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGiftServiceServer struct{}

func (UnimplementedGiftServiceServer) SendGift(context.Context, *SendGiftRequest) (*SendGiftResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendGift not implemented")
}
func (UnimplementedGiftServiceServer) ListGifts(context.Context, *ListGiftsRequest) (*ListGiftsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGifts not implemented")
}
func (UnimplementedGiftServiceServer) mustEmbedUnimplementedGiftServiceServer() {}
func (UnimplementedGiftServiceServer) testEmbeddedByValue()                     {}

// UnsafeGiftServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GiftServiceServer will
// result in compilation errors.
type UnsafeGiftServiceServer interface {
	mustEmbedUnimplementedGiftServiceServer()
}

func RegisterGiftServiceServer(s grpc.ServiceRegistrar, srv GiftServiceServer) {
	// If the following call panics, it indicates UnimplementedGiftServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GiftService_ServiceDesc, srv)
}

func _GiftService_SendGift_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendGiftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GiftServiceServer).SendGift(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GiftService_SendGift_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GiftServiceServer).SendGift(ctx, req.(*SendGiftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GiftService_ListGifts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGiftsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GiftServiceServer).ListGifts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GiftService_ListGifts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GiftServiceServer).ListGifts(ctx, req.(*ListGiftsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GiftService_ServiceDesc is the grpc.ServiceDesc for GiftService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GiftService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gift.GiftService",
	HandlerType: (*GiftServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendGift",
			Handler:    _GiftService_SendGift_Handler,
		},
		{
			MethodName: "ListGifts",
			Handler:    _GiftService_ListGifts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gift/gift_service.proto",
}

const (
	GiftRecordService_GetGiftRecord_FullMethodName         = "/gift.GiftRecordService/GetGiftRecord"
	GiftRecordService_ListGiftRecordsByRoom_FullMethodName = "/gift.GiftRecordService/ListGiftRecordsByRoom"
)

// GiftRecordServiceClient is the client API for GiftRecordService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ==================== Internal Service（内部调用）====================
type GiftRecordServiceClient interface {
	// 根据幂等性 key 查询礼物记录
	GetGiftRecord(ctx context.Context, in *GetGiftRecordRequest, opts ...grpc.CallOption) (*GetGiftRecordResponse, error)
	// 查询房间内的礼物流水（支持分页）
	ListGiftRecordsByRoom(ctx context.Context, in *ListGiftRecordsByRoomRequest, opts ...grpc.CallOption) (*ListGiftRecordsByRoomResponse, error)
}

type giftRecordServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGiftRecordServiceClient(cc grpc.ClientConnInterface) GiftRecordServiceClient {
	return &giftRecordServiceClient{cc}
}

func (c *giftRecordServiceClient) GetGiftRecord(ctx context.Context, in *GetGiftRecordRequest, opts ...grpc.CallOption) (*GetGiftRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGiftRecordResponse)
	err := c.cc.Invoke(ctx, GiftRecordService_GetGiftRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *giftRecordServiceClient) ListGiftRecordsByRoom(ctx context.Context, in *ListGiftRecordsByRoomRequest, opts ...grpc.CallOption) (*ListGiftRecordsByRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGiftRecordsByRoomResponse)
	err := c.cc.Invoke(ctx, GiftRecordService_ListGiftRecordsByRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GiftRecordServiceServer is the server API for GiftRecordService service.
// All implementations must embed UnimplementedGiftRecordServiceServer
// for forward compatibility.
//
// ==================== Internal Service（内部调用）====================
type GiftRecordServiceServer interface {
	// 根据幂等性 key 查询礼物记录
	GetGiftRecord(context.Context, *GetGiftRecordRequest) (*GetGiftRecordResponse, error)
	// 查询房间内的礼物流水（支持分页）
	ListGiftRecordsByRoom(context.Context, *ListGiftRecordsByRoomRequest) (*ListGiftRecordsByRoomResponse, error)
	mustEmbedUnimplementedGiftRecordServiceServer()
}

// UnimplementedGiftRecordServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGiftRecordServiceServer struct{}

func (UnimplementedGiftRecordServiceServer) GetGiftRecord(context.Context, *GetGiftRecordRequest) (*GetGiftRecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGiftRecord not implemented")
}
func (UnimplementedGiftRecordServiceServer) ListGiftRecordsByRoom(context.Context, *ListGiftRecordsByRoomRequest) (*ListGiftRecordsByRoomResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGiftRecordsByRoom not implemented")
}
func (UnimplementedGiftRecordServiceServer) mustEmbedUnimplementedGiftRecordServiceServer() {}
func (UnimplementedGiftRecordServiceServer) testEmbeddedByValue()                           {}

// UnsafeGiftRecordServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GiftRecordServiceServer will
// result in compilation errors.
type UnsafeGiftRecordServiceServer interface {
	mustEmbedUnimplementedGiftRecordServiceServer()
}

func RegisterGiftRecordServiceServer(s grpc.ServiceRegistrar, srv GiftRecordServiceServer) {
	// If the following call panics, it indicates UnimplementedGiftRecordServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GiftRecordService_ServiceDesc, srv)
}

func _GiftRecordService_GetGiftRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGiftRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GiftRecordServiceServer).GetGiftRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GiftRecordService_GetGiftRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GiftRecordServiceServer).GetGiftRecord(ctx, req.(*GetGiftRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GiftRecordService_ListGiftRecordsByRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGiftRecordsByRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GiftRecordServiceServer).ListGiftRecordsByRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GiftRecordService_ListGiftRecordsByRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GiftRecordServiceServer).ListGiftRecordsByRoom(ctx, req.(*ListGiftRecordsByRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GiftRecordService_ServiceDesc is the grpc.ServiceDesc for GiftRecordService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GiftRecordService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gift.GiftRecordService",
	HandlerType: (*GiftRecordServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGiftRecord",
			Handler:    _GiftRecordService_GetGiftRecord_Handler,
		},
		{
			MethodName: "ListGiftRecordsByRoom",
			Handler:    _GiftRecordService_ListGiftRecordsByRoom_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gift/gift_service.proto",
}
