// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: gift/wallet_service.proto

package gift

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_gift_wallet_service_proto protoreflect.FileDescriptor

const file_gift_wallet_service_proto_rawDesc = "" +
	"\n" +
	"\x19gift/wallet_service.proto\x12\x04gift\x1a\x13gift/gift_api.proto2b\n" +
	"\rWalletService\x12Q\n" +
	"\x10GetWalletBalance\x12\x1d.gift.GetWalletBalanceRequest\x1a\x1e.gift.GetWalletBalanceResponseB\x18Z\x16shared/proto/gift;giftb\x06proto3"

var file_gift_wallet_service_proto_goTypes = []any{
	(*GetWalletBalanceRequest)(nil),  // 0: gift.GetWalletBalanceRequest
	(*GetWalletBalanceResponse)(nil), // 1: gift.GetWalletBalanceResponse
}
var file_gift_wallet_service_proto_depIdxs = []int32{
	0, // 0: gift.WalletService.GetWalletBalance:input_type -> gift.GetWalletBalanceRequest
	1, // 1: gift.WalletService.GetWalletBalance:output_type -> gift.GetWalletBalanceResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gift_wallet_service_proto_init() }
func file_gift_wallet_service_proto_init() {
	if File_gift_wallet_service_proto != nil {
		return
	}
	file_gift_gift_api_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gift_wallet_service_proto_rawDesc), len(file_gift_wallet_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gift_wallet_service_proto_goTypes,
		DependencyIndexes: file_gift_wallet_service_proto_depIdxs,
	}.Build()
	File_gift_wallet_service_proto = out.File
	file_gift_wallet_service_proto_goTypes = nil
	file_gift_wallet_service_proto_depIdxs = nil
}
