// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: gift/wallet_service.proto

package gift

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitializeWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeWalletRequest) Reset() {
	*x = InitializeWalletRequest{}
	mi := &file_gift_wallet_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeWalletRequest) ProtoMessage() {}

func (x *InitializeWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gift_wallet_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeWalletRequest.ProtoReflect.Descriptor instead.
func (*InitializeWalletRequest) Descriptor() ([]byte, []int) {
	return file_gift_wallet_service_proto_rawDescGZIP(), []int{0}
}

func (x *InitializeWalletRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type InitializeWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeWalletResponse) Reset() {
	*x = InitializeWalletResponse{}
	mi := &file_gift_wallet_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeWalletResponse) ProtoMessage() {}

func (x *InitializeWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gift_wallet_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeWalletResponse.ProtoReflect.Descriptor instead.
func (*InitializeWalletResponse) Descriptor() ([]byte, []int) {
	return file_gift_wallet_service_proto_rawDescGZIP(), []int{1}
}

func (x *InitializeWalletResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RechargeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // UUID
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`              // 充值金额
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RechargeRequest) Reset() {
	*x = RechargeRequest{}
	mi := &file_gift_wallet_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RechargeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeRequest) ProtoMessage() {}

func (x *RechargeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gift_wallet_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeRequest.ProtoReflect.Descriptor instead.
func (*RechargeRequest) Descriptor() ([]byte, []int) {
	return file_gift_wallet_service_proto_rawDescGZIP(), []int{2}
}

func (x *RechargeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RechargeRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type RechargeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewBalance    int64                  `protobuf:"varint,1,opt,name=new_balance,json=newBalance,proto3" json:"new_balance,omitempty"` // 充值后的余额
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RechargeResponse) Reset() {
	*x = RechargeResponse{}
	mi := &file_gift_wallet_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RechargeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeResponse) ProtoMessage() {}

func (x *RechargeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gift_wallet_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeResponse.ProtoReflect.Descriptor instead.
func (*RechargeResponse) Descriptor() ([]byte, []int) {
	return file_gift_wallet_service_proto_rawDescGZIP(), []int{3}
}

func (x *RechargeResponse) GetNewBalance() int64 {
	if x != nil {
		return x.NewBalance
	}
	return 0
}

var File_gift_wallet_service_proto protoreflect.FileDescriptor

const file_gift_wallet_service_proto_rawDesc = "" +
	"\n" +
	"\x19gift/wallet_service.proto\x12\x04gift\x1a\x13gift/gift_api.proto\"2\n" +
	"\x17InitializeWalletRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"4\n" +
	"\x18InitializeWalletResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"B\n" +
	"\x0fRechargeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"3\n" +
	"\x10RechargeResponse\x12\x1f\n" +
	"\vnew_balance\x18\x01 \x01(\x03R\n" +
	"newBalance2\xf0\x01\n" +
	"\rWalletService\x12Q\n" +
	"\x10GetWalletBalance\x12\x1d.gift.GetWalletBalanceRequest\x1a\x1e.gift.GetWalletBalanceResponse\x12Q\n" +
	"\x10InitializeWallet\x12\x1d.gift.InitializeWalletRequest\x1a\x1e.gift.InitializeWalletResponse\x129\n" +
	"\bRecharge\x12\x15.gift.RechargeRequest\x1a\x16.gift.RechargeResponseB\x18Z\x16shared/proto/gift;giftb\x06proto3"

var (
	file_gift_wallet_service_proto_rawDescOnce sync.Once
	file_gift_wallet_service_proto_rawDescData []byte
)

func file_gift_wallet_service_proto_rawDescGZIP() []byte {
	file_gift_wallet_service_proto_rawDescOnce.Do(func() {
		file_gift_wallet_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gift_wallet_service_proto_rawDesc), len(file_gift_wallet_service_proto_rawDesc)))
	})
	return file_gift_wallet_service_proto_rawDescData
}

var file_gift_wallet_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gift_wallet_service_proto_goTypes = []any{
	(*InitializeWalletRequest)(nil),  // 0: gift.InitializeWalletRequest
	(*InitializeWalletResponse)(nil), // 1: gift.InitializeWalletResponse
	(*RechargeRequest)(nil),          // 2: gift.RechargeRequest
	(*RechargeResponse)(nil),         // 3: gift.RechargeResponse
	(*GetWalletBalanceRequest)(nil),  // 4: gift.GetWalletBalanceRequest
	(*GetWalletBalanceResponse)(nil), // 5: gift.GetWalletBalanceResponse
}
var file_gift_wallet_service_proto_depIdxs = []int32{
	4, // 0: gift.WalletService.GetWalletBalance:input_type -> gift.GetWalletBalanceRequest
	0, // 1: gift.WalletService.InitializeWallet:input_type -> gift.InitializeWalletRequest
	2, // 2: gift.WalletService.Recharge:input_type -> gift.RechargeRequest
	5, // 3: gift.WalletService.GetWalletBalance:output_type -> gift.GetWalletBalanceResponse
	1, // 4: gift.WalletService.InitializeWallet:output_type -> gift.InitializeWalletResponse
	3, // 5: gift.WalletService.Recharge:output_type -> gift.RechargeResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gift_wallet_service_proto_init() }
func file_gift_wallet_service_proto_init() {
	if File_gift_wallet_service_proto != nil {
		return
	}
	file_gift_gift_api_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gift_wallet_service_proto_rawDesc), len(file_gift_wallet_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gift_wallet_service_proto_goTypes,
		DependencyIndexes: file_gift_wallet_service_proto_depIdxs,
		MessageInfos:      file_gift_wallet_service_proto_msgTypes,
	}.Build()
	File_gift_wallet_service_proto = out.File
	file_gift_wallet_service_proto_goTypes = nil
	file_gift_wallet_service_proto_depIdxs = nil
}
