// Code generated by ent, DO NOT EDIT.

package ent

import (
	"live-interact-engine/services/gift-service/ent/gift"
	"live-interact-engine/services/gift-service/ent/schema"
	"live-interact-engine/services/gift-service/ent/wallet"
	"live-interact-engine/services/gift-service/ent/wallettransaction"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	giftFields := schema.Gift{}.Fields()
	_ = giftFields
	// giftDescName is the schema descriptor for name field.
	giftDescName := giftFields[1].Descriptor()
	// gift.NameValidator is a validator for the "name" field. It is called by the builders before save.
	gift.NameValidator = func() func(string) error {
		validators := giftDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
			validators[2].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// giftDescDescription is the schema descriptor for description field.
	giftDescDescription := giftFields[2].Descriptor()
	// gift.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	gift.DescriptionValidator = giftDescDescription.Validators[0].(func(string) error)
	// giftDescIconURL is the schema descriptor for icon_url field.
	giftDescIconURL := giftFields[3].Descriptor()
	// gift.IconURLValidator is a validator for the "icon_url" field. It is called by the builders before save.
	gift.IconURLValidator = giftDescIconURL.Validators[0].(func(string) error)
	// giftDescPrice is the schema descriptor for price field.
	giftDescPrice := giftFields[5].Descriptor()
	// gift.PriceValidator is a validator for the "price" field. It is called by the builders before save.
	gift.PriceValidator = giftDescPrice.Validators[0].(func(int64) error)
	// giftDescVipOnly is the schema descriptor for vip_only field.
	giftDescVipOnly := giftFields[6].Descriptor()
	// gift.DefaultVipOnly holds the default value on creation for the vip_only field.
	gift.DefaultVipOnly = giftDescVipOnly.Default.(bool)
	// giftDescCreatedAt is the schema descriptor for created_at field.
	giftDescCreatedAt := giftFields[8].Descriptor()
	// gift.DefaultCreatedAt holds the default value on creation for the created_at field.
	gift.DefaultCreatedAt = giftDescCreatedAt.Default.(func() time.Time)
	// giftDescUpdatedAt is the schema descriptor for updated_at field.
	giftDescUpdatedAt := giftFields[9].Descriptor()
	// gift.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	gift.DefaultUpdatedAt = giftDescUpdatedAt.Default.(func() time.Time)
	// gift.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	gift.UpdateDefaultUpdatedAt = giftDescUpdatedAt.UpdateDefault.(func() time.Time)
	// giftDescID is the schema descriptor for id field.
	giftDescID := giftFields[0].Descriptor()
	// gift.DefaultID holds the default value on creation for the id field.
	gift.DefaultID = giftDescID.Default.(func() uuid.UUID)
	walletFields := schema.Wallet{}.Fields()
	_ = walletFields
	// walletDescBalance is the schema descriptor for balance field.
	walletDescBalance := walletFields[1].Descriptor()
	// wallet.DefaultBalance holds the default value on creation for the balance field.
	wallet.DefaultBalance = walletDescBalance.Default.(int64)
	// walletDescVersionNumber is the schema descriptor for version_number field.
	walletDescVersionNumber := walletFields[2].Descriptor()
	// wallet.DefaultVersionNumber holds the default value on creation for the version_number field.
	wallet.DefaultVersionNumber = walletDescVersionNumber.Default.(int64)
	// walletDescCreatedAt is the schema descriptor for created_at field.
	walletDescCreatedAt := walletFields[3].Descriptor()
	// wallet.DefaultCreatedAt holds the default value on creation for the created_at field.
	wallet.DefaultCreatedAt = walletDescCreatedAt.Default.(func() time.Time)
	// walletDescUpdatedAt is the schema descriptor for updated_at field.
	walletDescUpdatedAt := walletFields[4].Descriptor()
	// wallet.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	wallet.DefaultUpdatedAt = walletDescUpdatedAt.Default.(func() time.Time)
	// wallet.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	wallet.UpdateDefaultUpdatedAt = walletDescUpdatedAt.UpdateDefault.(func() time.Time)
	wallettransactionFields := schema.WalletTransaction{}.Fields()
	_ = wallettransactionFields
	// wallettransactionDescStatus is the schema descriptor for status field.
	wallettransactionDescStatus := wallettransactionFields[7].Descriptor()
	// wallettransaction.DefaultStatus holds the default value on creation for the status field.
	wallettransaction.DefaultStatus = wallettransactionDescStatus.Default.(string)
	// wallettransactionDescCreatedAt is the schema descriptor for created_at field.
	wallettransactionDescCreatedAt := wallettransactionFields[8].Descriptor()
	// wallettransaction.DefaultCreatedAt holds the default value on creation for the created_at field.
	wallettransaction.DefaultCreatedAt = wallettransactionDescCreatedAt.Default.(func() time.Time)
	// wallettransactionDescUpdatedAt is the schema descriptor for updated_at field.
	wallettransactionDescUpdatedAt := wallettransactionFields[9].Descriptor()
	// wallettransaction.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	wallettransaction.DefaultUpdatedAt = wallettransactionDescUpdatedAt.Default.(func() time.Time)
	// wallettransaction.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	wallettransaction.UpdateDefaultUpdatedAt = wallettransactionDescUpdatedAt.UpdateDefault.(func() time.Time)
}
