// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"live-interact-engine/services/gift-service/ent/wallettransaction"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// WalletTransactionCreate is the builder for creating a WalletTransaction entity.
type WalletTransactionCreate struct {
	config
	mutation *WalletTransactionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_c *WalletTransactionCreate) SetIdempotencyKey(v uuid.UUID) *WalletTransactionCreate {
	_c.mutation.SetIdempotencyKey(v)
	return _c
}

// SetType sets the "type" field.
func (_c *WalletTransactionCreate) SetType(v int) *WalletTransactionCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetPayerID sets the "payer_id" field.
func (_c *WalletTransactionCreate) SetPayerID(v uuid.UUID) *WalletTransactionCreate {
	_c.mutation.SetPayerID(v)
	return _c
}

// SetPayeeID sets the "payee_id" field.
func (_c *WalletTransactionCreate) SetPayeeID(v uuid.UUID) *WalletTransactionCreate {
	_c.mutation.SetPayeeID(v)
	return _c
}

// SetNillablePayeeID sets the "payee_id" field if the given value is not nil.
func (_c *WalletTransactionCreate) SetNillablePayeeID(v *uuid.UUID) *WalletTransactionCreate {
	if v != nil {
		_c.SetPayeeID(*v)
	}
	return _c
}

// SetAmount sets the "amount" field.
func (_c *WalletTransactionCreate) SetAmount(v int64) *WalletTransactionCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetRoomID sets the "room_id" field.
func (_c *WalletTransactionCreate) SetRoomID(v uuid.UUID) *WalletTransactionCreate {
	_c.mutation.SetRoomID(v)
	return _c
}

// SetNillableRoomID sets the "room_id" field if the given value is not nil.
func (_c *WalletTransactionCreate) SetNillableRoomID(v *uuid.UUID) *WalletTransactionCreate {
	if v != nil {
		_c.SetRoomID(*v)
	}
	return _c
}

// SetGiftID sets the "gift_id" field.
func (_c *WalletTransactionCreate) SetGiftID(v uuid.UUID) *WalletTransactionCreate {
	_c.mutation.SetGiftID(v)
	return _c
}

// SetNillableGiftID sets the "gift_id" field if the given value is not nil.
func (_c *WalletTransactionCreate) SetNillableGiftID(v *uuid.UUID) *WalletTransactionCreate {
	if v != nil {
		_c.SetGiftID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *WalletTransactionCreate) SetStatus(v string) *WalletTransactionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *WalletTransactionCreate) SetNillableStatus(v *string) *WalletTransactionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *WalletTransactionCreate) SetCreatedAt(v time.Time) *WalletTransactionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WalletTransactionCreate) SetNillableCreatedAt(v *time.Time) *WalletTransactionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *WalletTransactionCreate) SetUpdatedAt(v time.Time) *WalletTransactionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *WalletTransactionCreate) SetNillableUpdatedAt(v *time.Time) *WalletTransactionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the WalletTransactionMutation object of the builder.
func (_c *WalletTransactionCreate) Mutation() *WalletTransactionMutation {
	return _c.mutation
}

// Save creates the WalletTransaction in the database.
func (_c *WalletTransactionCreate) Save(ctx context.Context) (*WalletTransaction, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WalletTransactionCreate) SaveX(ctx context.Context) *WalletTransaction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WalletTransactionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WalletTransactionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WalletTransactionCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := wallettransaction.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := wallettransaction.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := wallettransaction.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WalletTransactionCreate) check() error {
	if _, ok := _c.mutation.IdempotencyKey(); !ok {
		return &ValidationError{Name: "idempotency_key", err: errors.New(`ent: missing required field "WalletTransaction.idempotency_key"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "WalletTransaction.type"`)}
	}
	if _, ok := _c.mutation.PayerID(); !ok {
		return &ValidationError{Name: "payer_id", err: errors.New(`ent: missing required field "WalletTransaction.payer_id"`)}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "WalletTransaction.amount"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "WalletTransaction.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "WalletTransaction.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "WalletTransaction.updated_at"`)}
	}
	return nil
}

func (_c *WalletTransactionCreate) sqlSave(ctx context.Context) (*WalletTransaction, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WalletTransactionCreate) createSpec() (*WalletTransaction, *sqlgraph.CreateSpec) {
	var (
		_node = &WalletTransaction{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(wallettransaction.Table, sqlgraph.NewFieldSpec(wallettransaction.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.IdempotencyKey(); ok {
		_spec.SetField(wallettransaction.FieldIdempotencyKey, field.TypeUUID, value)
		_node.IdempotencyKey = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(wallettransaction.FieldType, field.TypeInt, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.PayerID(); ok {
		_spec.SetField(wallettransaction.FieldPayerID, field.TypeUUID, value)
		_node.PayerID = value
	}
	if value, ok := _c.mutation.PayeeID(); ok {
		_spec.SetField(wallettransaction.FieldPayeeID, field.TypeUUID, value)
		_node.PayeeID = &value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(wallettransaction.FieldAmount, field.TypeInt64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.RoomID(); ok {
		_spec.SetField(wallettransaction.FieldRoomID, field.TypeUUID, value)
		_node.RoomID = &value
	}
	if value, ok := _c.mutation.GiftID(); ok {
		_spec.SetField(wallettransaction.FieldGiftID, field.TypeUUID, value)
		_node.GiftID = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(wallettransaction.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(wallettransaction.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(wallettransaction.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WalletTransaction.Create().
//		SetIdempotencyKey(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WalletTransactionUpsert) {
//			SetIdempotencyKey(v+v).
//		}).
//		Exec(ctx)
func (_c *WalletTransactionCreate) OnConflict(opts ...sql.ConflictOption) *WalletTransactionUpsertOne {
	_c.conflict = opts
	return &WalletTransactionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WalletTransaction.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WalletTransactionCreate) OnConflictColumns(columns ...string) *WalletTransactionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WalletTransactionUpsertOne{
		create: _c,
	}
}

type (
	// WalletTransactionUpsertOne is the builder for "upsert"-ing
	//  one WalletTransaction node.
	WalletTransactionUpsertOne struct {
		create *WalletTransactionCreate
	}

	// WalletTransactionUpsert is the "OnConflict" setter.
	WalletTransactionUpsert struct {
		*sql.UpdateSet
	}
)

// SetType sets the "type" field.
func (u *WalletTransactionUpsert) SetType(v int) *WalletTransactionUpsert {
	u.Set(wallettransaction.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *WalletTransactionUpsert) UpdateType() *WalletTransactionUpsert {
	u.SetExcluded(wallettransaction.FieldType)
	return u
}

// AddType adds v to the "type" field.
func (u *WalletTransactionUpsert) AddType(v int) *WalletTransactionUpsert {
	u.Add(wallettransaction.FieldType, v)
	return u
}

// SetPayerID sets the "payer_id" field.
func (u *WalletTransactionUpsert) SetPayerID(v uuid.UUID) *WalletTransactionUpsert {
	u.Set(wallettransaction.FieldPayerID, v)
	return u
}

// UpdatePayerID sets the "payer_id" field to the value that was provided on create.
func (u *WalletTransactionUpsert) UpdatePayerID() *WalletTransactionUpsert {
	u.SetExcluded(wallettransaction.FieldPayerID)
	return u
}

// SetPayeeID sets the "payee_id" field.
func (u *WalletTransactionUpsert) SetPayeeID(v uuid.UUID) *WalletTransactionUpsert {
	u.Set(wallettransaction.FieldPayeeID, v)
	return u
}

// UpdatePayeeID sets the "payee_id" field to the value that was provided on create.
func (u *WalletTransactionUpsert) UpdatePayeeID() *WalletTransactionUpsert {
	u.SetExcluded(wallettransaction.FieldPayeeID)
	return u
}

// ClearPayeeID clears the value of the "payee_id" field.
func (u *WalletTransactionUpsert) ClearPayeeID() *WalletTransactionUpsert {
	u.SetNull(wallettransaction.FieldPayeeID)
	return u
}

// SetAmount sets the "amount" field.
func (u *WalletTransactionUpsert) SetAmount(v int64) *WalletTransactionUpsert {
	u.Set(wallettransaction.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *WalletTransactionUpsert) UpdateAmount() *WalletTransactionUpsert {
	u.SetExcluded(wallettransaction.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *WalletTransactionUpsert) AddAmount(v int64) *WalletTransactionUpsert {
	u.Add(wallettransaction.FieldAmount, v)
	return u
}

// SetRoomID sets the "room_id" field.
func (u *WalletTransactionUpsert) SetRoomID(v uuid.UUID) *WalletTransactionUpsert {
	u.Set(wallettransaction.FieldRoomID, v)
	return u
}

// UpdateRoomID sets the "room_id" field to the value that was provided on create.
func (u *WalletTransactionUpsert) UpdateRoomID() *WalletTransactionUpsert {
	u.SetExcluded(wallettransaction.FieldRoomID)
	return u
}

// ClearRoomID clears the value of the "room_id" field.
func (u *WalletTransactionUpsert) ClearRoomID() *WalletTransactionUpsert {
	u.SetNull(wallettransaction.FieldRoomID)
	return u
}

// SetGiftID sets the "gift_id" field.
func (u *WalletTransactionUpsert) SetGiftID(v uuid.UUID) *WalletTransactionUpsert {
	u.Set(wallettransaction.FieldGiftID, v)
	return u
}

// UpdateGiftID sets the "gift_id" field to the value that was provided on create.
func (u *WalletTransactionUpsert) UpdateGiftID() *WalletTransactionUpsert {
	u.SetExcluded(wallettransaction.FieldGiftID)
	return u
}

// ClearGiftID clears the value of the "gift_id" field.
func (u *WalletTransactionUpsert) ClearGiftID() *WalletTransactionUpsert {
	u.SetNull(wallettransaction.FieldGiftID)
	return u
}

// SetStatus sets the "status" field.
func (u *WalletTransactionUpsert) SetStatus(v string) *WalletTransactionUpsert {
	u.Set(wallettransaction.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *WalletTransactionUpsert) UpdateStatus() *WalletTransactionUpsert {
	u.SetExcluded(wallettransaction.FieldStatus)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WalletTransactionUpsert) SetUpdatedAt(v time.Time) *WalletTransactionUpsert {
	u.Set(wallettransaction.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WalletTransactionUpsert) UpdateUpdatedAt() *WalletTransactionUpsert {
	u.SetExcluded(wallettransaction.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.WalletTransaction.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WalletTransactionUpsertOne) UpdateNewValues() *WalletTransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.IdempotencyKey(); exists {
			s.SetIgnore(wallettransaction.FieldIdempotencyKey)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(wallettransaction.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WalletTransaction.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *WalletTransactionUpsertOne) Ignore() *WalletTransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WalletTransactionUpsertOne) DoNothing() *WalletTransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WalletTransactionCreate.OnConflict
// documentation for more info.
func (u *WalletTransactionUpsertOne) Update(set func(*WalletTransactionUpsert)) *WalletTransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WalletTransactionUpsert{UpdateSet: update})
	}))
	return u
}

// SetType sets the "type" field.
func (u *WalletTransactionUpsertOne) SetType(v int) *WalletTransactionUpsertOne {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.SetType(v)
	})
}

// AddType adds v to the "type" field.
func (u *WalletTransactionUpsertOne) AddType(v int) *WalletTransactionUpsertOne {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.AddType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *WalletTransactionUpsertOne) UpdateType() *WalletTransactionUpsertOne {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.UpdateType()
	})
}

// SetPayerID sets the "payer_id" field.
func (u *WalletTransactionUpsertOne) SetPayerID(v uuid.UUID) *WalletTransactionUpsertOne {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.SetPayerID(v)
	})
}

// UpdatePayerID sets the "payer_id" field to the value that was provided on create.
func (u *WalletTransactionUpsertOne) UpdatePayerID() *WalletTransactionUpsertOne {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.UpdatePayerID()
	})
}

// SetPayeeID sets the "payee_id" field.
func (u *WalletTransactionUpsertOne) SetPayeeID(v uuid.UUID) *WalletTransactionUpsertOne {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.SetPayeeID(v)
	})
}

// UpdatePayeeID sets the "payee_id" field to the value that was provided on create.
func (u *WalletTransactionUpsertOne) UpdatePayeeID() *WalletTransactionUpsertOne {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.UpdatePayeeID()
	})
}

// ClearPayeeID clears the value of the "payee_id" field.
func (u *WalletTransactionUpsertOne) ClearPayeeID() *WalletTransactionUpsertOne {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.ClearPayeeID()
	})
}

// SetAmount sets the "amount" field.
func (u *WalletTransactionUpsertOne) SetAmount(v int64) *WalletTransactionUpsertOne {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *WalletTransactionUpsertOne) AddAmount(v int64) *WalletTransactionUpsertOne {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *WalletTransactionUpsertOne) UpdateAmount() *WalletTransactionUpsertOne {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.UpdateAmount()
	})
}

// SetRoomID sets the "room_id" field.
func (u *WalletTransactionUpsertOne) SetRoomID(v uuid.UUID) *WalletTransactionUpsertOne {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.SetRoomID(v)
	})
}

// UpdateRoomID sets the "room_id" field to the value that was provided on create.
func (u *WalletTransactionUpsertOne) UpdateRoomID() *WalletTransactionUpsertOne {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.UpdateRoomID()
	})
}

// ClearRoomID clears the value of the "room_id" field.
func (u *WalletTransactionUpsertOne) ClearRoomID() *WalletTransactionUpsertOne {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.ClearRoomID()
	})
}

// SetGiftID sets the "gift_id" field.
func (u *WalletTransactionUpsertOne) SetGiftID(v uuid.UUID) *WalletTransactionUpsertOne {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.SetGiftID(v)
	})
}

// UpdateGiftID sets the "gift_id" field to the value that was provided on create.
func (u *WalletTransactionUpsertOne) UpdateGiftID() *WalletTransactionUpsertOne {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.UpdateGiftID()
	})
}

// ClearGiftID clears the value of the "gift_id" field.
func (u *WalletTransactionUpsertOne) ClearGiftID() *WalletTransactionUpsertOne {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.ClearGiftID()
	})
}

// SetStatus sets the "status" field.
func (u *WalletTransactionUpsertOne) SetStatus(v string) *WalletTransactionUpsertOne {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *WalletTransactionUpsertOne) UpdateStatus() *WalletTransactionUpsertOne {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.UpdateStatus()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WalletTransactionUpsertOne) SetUpdatedAt(v time.Time) *WalletTransactionUpsertOne {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WalletTransactionUpsertOne) UpdateUpdatedAt() *WalletTransactionUpsertOne {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *WalletTransactionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WalletTransactionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WalletTransactionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *WalletTransactionUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *WalletTransactionUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// WalletTransactionCreateBulk is the builder for creating many WalletTransaction entities in bulk.
type WalletTransactionCreateBulk struct {
	config
	err      error
	builders []*WalletTransactionCreate
	conflict []sql.ConflictOption
}

// Save creates the WalletTransaction entities in the database.
func (_c *WalletTransactionCreateBulk) Save(ctx context.Context) ([]*WalletTransaction, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WalletTransaction, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WalletTransactionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WalletTransactionCreateBulk) SaveX(ctx context.Context) []*WalletTransaction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WalletTransactionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WalletTransactionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WalletTransaction.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WalletTransactionUpsert) {
//			SetIdempotencyKey(v+v).
//		}).
//		Exec(ctx)
func (_c *WalletTransactionCreateBulk) OnConflict(opts ...sql.ConflictOption) *WalletTransactionUpsertBulk {
	_c.conflict = opts
	return &WalletTransactionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WalletTransaction.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WalletTransactionCreateBulk) OnConflictColumns(columns ...string) *WalletTransactionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WalletTransactionUpsertBulk{
		create: _c,
	}
}

// WalletTransactionUpsertBulk is the builder for "upsert"-ing
// a bulk of WalletTransaction nodes.
type WalletTransactionUpsertBulk struct {
	create *WalletTransactionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.WalletTransaction.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WalletTransactionUpsertBulk) UpdateNewValues() *WalletTransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.IdempotencyKey(); exists {
				s.SetIgnore(wallettransaction.FieldIdempotencyKey)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(wallettransaction.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WalletTransaction.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *WalletTransactionUpsertBulk) Ignore() *WalletTransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WalletTransactionUpsertBulk) DoNothing() *WalletTransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WalletTransactionCreateBulk.OnConflict
// documentation for more info.
func (u *WalletTransactionUpsertBulk) Update(set func(*WalletTransactionUpsert)) *WalletTransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WalletTransactionUpsert{UpdateSet: update})
	}))
	return u
}

// SetType sets the "type" field.
func (u *WalletTransactionUpsertBulk) SetType(v int) *WalletTransactionUpsertBulk {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.SetType(v)
	})
}

// AddType adds v to the "type" field.
func (u *WalletTransactionUpsertBulk) AddType(v int) *WalletTransactionUpsertBulk {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.AddType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *WalletTransactionUpsertBulk) UpdateType() *WalletTransactionUpsertBulk {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.UpdateType()
	})
}

// SetPayerID sets the "payer_id" field.
func (u *WalletTransactionUpsertBulk) SetPayerID(v uuid.UUID) *WalletTransactionUpsertBulk {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.SetPayerID(v)
	})
}

// UpdatePayerID sets the "payer_id" field to the value that was provided on create.
func (u *WalletTransactionUpsertBulk) UpdatePayerID() *WalletTransactionUpsertBulk {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.UpdatePayerID()
	})
}

// SetPayeeID sets the "payee_id" field.
func (u *WalletTransactionUpsertBulk) SetPayeeID(v uuid.UUID) *WalletTransactionUpsertBulk {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.SetPayeeID(v)
	})
}

// UpdatePayeeID sets the "payee_id" field to the value that was provided on create.
func (u *WalletTransactionUpsertBulk) UpdatePayeeID() *WalletTransactionUpsertBulk {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.UpdatePayeeID()
	})
}

// ClearPayeeID clears the value of the "payee_id" field.
func (u *WalletTransactionUpsertBulk) ClearPayeeID() *WalletTransactionUpsertBulk {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.ClearPayeeID()
	})
}

// SetAmount sets the "amount" field.
func (u *WalletTransactionUpsertBulk) SetAmount(v int64) *WalletTransactionUpsertBulk {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *WalletTransactionUpsertBulk) AddAmount(v int64) *WalletTransactionUpsertBulk {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *WalletTransactionUpsertBulk) UpdateAmount() *WalletTransactionUpsertBulk {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.UpdateAmount()
	})
}

// SetRoomID sets the "room_id" field.
func (u *WalletTransactionUpsertBulk) SetRoomID(v uuid.UUID) *WalletTransactionUpsertBulk {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.SetRoomID(v)
	})
}

// UpdateRoomID sets the "room_id" field to the value that was provided on create.
func (u *WalletTransactionUpsertBulk) UpdateRoomID() *WalletTransactionUpsertBulk {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.UpdateRoomID()
	})
}

// ClearRoomID clears the value of the "room_id" field.
func (u *WalletTransactionUpsertBulk) ClearRoomID() *WalletTransactionUpsertBulk {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.ClearRoomID()
	})
}

// SetGiftID sets the "gift_id" field.
func (u *WalletTransactionUpsertBulk) SetGiftID(v uuid.UUID) *WalletTransactionUpsertBulk {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.SetGiftID(v)
	})
}

// UpdateGiftID sets the "gift_id" field to the value that was provided on create.
func (u *WalletTransactionUpsertBulk) UpdateGiftID() *WalletTransactionUpsertBulk {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.UpdateGiftID()
	})
}

// ClearGiftID clears the value of the "gift_id" field.
func (u *WalletTransactionUpsertBulk) ClearGiftID() *WalletTransactionUpsertBulk {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.ClearGiftID()
	})
}

// SetStatus sets the "status" field.
func (u *WalletTransactionUpsertBulk) SetStatus(v string) *WalletTransactionUpsertBulk {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *WalletTransactionUpsertBulk) UpdateStatus() *WalletTransactionUpsertBulk {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.UpdateStatus()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WalletTransactionUpsertBulk) SetUpdatedAt(v time.Time) *WalletTransactionUpsertBulk {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WalletTransactionUpsertBulk) UpdateUpdatedAt() *WalletTransactionUpsertBulk {
	return u.Update(func(s *WalletTransactionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *WalletTransactionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the WalletTransactionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WalletTransactionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WalletTransactionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
