// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"live-interact-engine/services/gift-service/ent/predicate"
	"live-interact-engine/services/gift-service/ent/wallet"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// WalletUpdate is the builder for updating Wallet entities.
type WalletUpdate struct {
	config
	hooks    []Hook
	mutation *WalletMutation
}

// Where appends a list predicates to the WalletUpdate builder.
func (_u *WalletUpdate) Where(ps ...predicate.Wallet) *WalletUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *WalletUpdate) SetUserID(v uuid.UUID) *WalletUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *WalletUpdate) SetNillableUserID(v *uuid.UUID) *WalletUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetBalance sets the "balance" field.
func (_u *WalletUpdate) SetBalance(v int64) *WalletUpdate {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *WalletUpdate) SetNillableBalance(v *int64) *WalletUpdate {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *WalletUpdate) AddBalance(v int64) *WalletUpdate {
	_u.mutation.AddBalance(v)
	return _u
}

// SetVersionNumber sets the "version_number" field.
func (_u *WalletUpdate) SetVersionNumber(v int64) *WalletUpdate {
	_u.mutation.ResetVersionNumber()
	_u.mutation.SetVersionNumber(v)
	return _u
}

// SetNillableVersionNumber sets the "version_number" field if the given value is not nil.
func (_u *WalletUpdate) SetNillableVersionNumber(v *int64) *WalletUpdate {
	if v != nil {
		_u.SetVersionNumber(*v)
	}
	return _u
}

// AddVersionNumber adds value to the "version_number" field.
func (_u *WalletUpdate) AddVersionNumber(v int64) *WalletUpdate {
	_u.mutation.AddVersionNumber(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WalletUpdate) SetUpdatedAt(v time.Time) *WalletUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the WalletMutation object of the builder.
func (_u *WalletUpdate) Mutation() *WalletMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WalletUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WalletUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WalletUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WalletUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WalletUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := wallet.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *WalletUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(wallet.Table, wallet.Columns, sqlgraph.NewFieldSpec(wallet.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(wallet.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(wallet.FieldBalance, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(wallet.FieldBalance, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.VersionNumber(); ok {
		_spec.SetField(wallet.FieldVersionNumber, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersionNumber(); ok {
		_spec.AddField(wallet.FieldVersionNumber, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(wallet.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wallet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WalletUpdateOne is the builder for updating a single Wallet entity.
type WalletUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WalletMutation
}

// SetUserID sets the "user_id" field.
func (_u *WalletUpdateOne) SetUserID(v uuid.UUID) *WalletUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *WalletUpdateOne) SetNillableUserID(v *uuid.UUID) *WalletUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetBalance sets the "balance" field.
func (_u *WalletUpdateOne) SetBalance(v int64) *WalletUpdateOne {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *WalletUpdateOne) SetNillableBalance(v *int64) *WalletUpdateOne {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *WalletUpdateOne) AddBalance(v int64) *WalletUpdateOne {
	_u.mutation.AddBalance(v)
	return _u
}

// SetVersionNumber sets the "version_number" field.
func (_u *WalletUpdateOne) SetVersionNumber(v int64) *WalletUpdateOne {
	_u.mutation.ResetVersionNumber()
	_u.mutation.SetVersionNumber(v)
	return _u
}

// SetNillableVersionNumber sets the "version_number" field if the given value is not nil.
func (_u *WalletUpdateOne) SetNillableVersionNumber(v *int64) *WalletUpdateOne {
	if v != nil {
		_u.SetVersionNumber(*v)
	}
	return _u
}

// AddVersionNumber adds value to the "version_number" field.
func (_u *WalletUpdateOne) AddVersionNumber(v int64) *WalletUpdateOne {
	_u.mutation.AddVersionNumber(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WalletUpdateOne) SetUpdatedAt(v time.Time) *WalletUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the WalletMutation object of the builder.
func (_u *WalletUpdateOne) Mutation() *WalletMutation {
	return _u.mutation
}

// Where appends a list predicates to the WalletUpdate builder.
func (_u *WalletUpdateOne) Where(ps ...predicate.Wallet) *WalletUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WalletUpdateOne) Select(field string, fields ...string) *WalletUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Wallet entity.
func (_u *WalletUpdateOne) Save(ctx context.Context) (*Wallet, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WalletUpdateOne) SaveX(ctx context.Context) *Wallet {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WalletUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WalletUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WalletUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := wallet.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *WalletUpdateOne) sqlSave(ctx context.Context) (_node *Wallet, err error) {
	_spec := sqlgraph.NewUpdateSpec(wallet.Table, wallet.Columns, sqlgraph.NewFieldSpec(wallet.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Wallet.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, wallet.FieldID)
		for _, f := range fields {
			if !wallet.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != wallet.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(wallet.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(wallet.FieldBalance, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(wallet.FieldBalance, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.VersionNumber(); ok {
		_spec.SetField(wallet.FieldVersionNumber, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersionNumber(); ok {
		_spec.AddField(wallet.FieldVersionNumber, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(wallet.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Wallet{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wallet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
