// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"live-interact-engine/services/gift-service/ent/wallet"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// WalletCreate is the builder for creating a Wallet entity.
type WalletCreate struct {
	config
	mutation *WalletMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *WalletCreate) SetUserID(v uuid.UUID) *WalletCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetBalance sets the "balance" field.
func (_c *WalletCreate) SetBalance(v int64) *WalletCreate {
	_c.mutation.SetBalance(v)
	return _c
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_c *WalletCreate) SetNillableBalance(v *int64) *WalletCreate {
	if v != nil {
		_c.SetBalance(*v)
	}
	return _c
}

// SetVersionNumber sets the "version_number" field.
func (_c *WalletCreate) SetVersionNumber(v int64) *WalletCreate {
	_c.mutation.SetVersionNumber(v)
	return _c
}

// SetNillableVersionNumber sets the "version_number" field if the given value is not nil.
func (_c *WalletCreate) SetNillableVersionNumber(v *int64) *WalletCreate {
	if v != nil {
		_c.SetVersionNumber(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *WalletCreate) SetCreatedAt(v time.Time) *WalletCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WalletCreate) SetNillableCreatedAt(v *time.Time) *WalletCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *WalletCreate) SetUpdatedAt(v time.Time) *WalletCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *WalletCreate) SetNillableUpdatedAt(v *time.Time) *WalletCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the WalletMutation object of the builder.
func (_c *WalletCreate) Mutation() *WalletMutation {
	return _c.mutation
}

// Save creates the Wallet in the database.
func (_c *WalletCreate) Save(ctx context.Context) (*Wallet, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WalletCreate) SaveX(ctx context.Context) *Wallet {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WalletCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WalletCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WalletCreate) defaults() {
	if _, ok := _c.mutation.Balance(); !ok {
		v := wallet.DefaultBalance
		_c.mutation.SetBalance(v)
	}
	if _, ok := _c.mutation.VersionNumber(); !ok {
		v := wallet.DefaultVersionNumber
		_c.mutation.SetVersionNumber(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := wallet.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := wallet.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WalletCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Wallet.user_id"`)}
	}
	if _, ok := _c.mutation.Balance(); !ok {
		return &ValidationError{Name: "balance", err: errors.New(`ent: missing required field "Wallet.balance"`)}
	}
	if _, ok := _c.mutation.VersionNumber(); !ok {
		return &ValidationError{Name: "version_number", err: errors.New(`ent: missing required field "Wallet.version_number"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Wallet.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Wallet.updated_at"`)}
	}
	return nil
}

func (_c *WalletCreate) sqlSave(ctx context.Context) (*Wallet, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WalletCreate) createSpec() (*Wallet, *sqlgraph.CreateSpec) {
	var (
		_node = &Wallet{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(wallet.Table, sqlgraph.NewFieldSpec(wallet.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(wallet.FieldUserID, field.TypeUUID, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Balance(); ok {
		_spec.SetField(wallet.FieldBalance, field.TypeInt64, value)
		_node.Balance = value
	}
	if value, ok := _c.mutation.VersionNumber(); ok {
		_spec.SetField(wallet.FieldVersionNumber, field.TypeInt64, value)
		_node.VersionNumber = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(wallet.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(wallet.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Wallet.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WalletUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *WalletCreate) OnConflict(opts ...sql.ConflictOption) *WalletUpsertOne {
	_c.conflict = opts
	return &WalletUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Wallet.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WalletCreate) OnConflictColumns(columns ...string) *WalletUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WalletUpsertOne{
		create: _c,
	}
}

type (
	// WalletUpsertOne is the builder for "upsert"-ing
	//  one Wallet node.
	WalletUpsertOne struct {
		create *WalletCreate
	}

	// WalletUpsert is the "OnConflict" setter.
	WalletUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *WalletUpsert) SetUserID(v uuid.UUID) *WalletUpsert {
	u.Set(wallet.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *WalletUpsert) UpdateUserID() *WalletUpsert {
	u.SetExcluded(wallet.FieldUserID)
	return u
}

// SetBalance sets the "balance" field.
func (u *WalletUpsert) SetBalance(v int64) *WalletUpsert {
	u.Set(wallet.FieldBalance, v)
	return u
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *WalletUpsert) UpdateBalance() *WalletUpsert {
	u.SetExcluded(wallet.FieldBalance)
	return u
}

// AddBalance adds v to the "balance" field.
func (u *WalletUpsert) AddBalance(v int64) *WalletUpsert {
	u.Add(wallet.FieldBalance, v)
	return u
}

// SetVersionNumber sets the "version_number" field.
func (u *WalletUpsert) SetVersionNumber(v int64) *WalletUpsert {
	u.Set(wallet.FieldVersionNumber, v)
	return u
}

// UpdateVersionNumber sets the "version_number" field to the value that was provided on create.
func (u *WalletUpsert) UpdateVersionNumber() *WalletUpsert {
	u.SetExcluded(wallet.FieldVersionNumber)
	return u
}

// AddVersionNumber adds v to the "version_number" field.
func (u *WalletUpsert) AddVersionNumber(v int64) *WalletUpsert {
	u.Add(wallet.FieldVersionNumber, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WalletUpsert) SetUpdatedAt(v time.Time) *WalletUpsert {
	u.Set(wallet.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WalletUpsert) UpdateUpdatedAt() *WalletUpsert {
	u.SetExcluded(wallet.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Wallet.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WalletUpsertOne) UpdateNewValues() *WalletUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(wallet.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Wallet.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *WalletUpsertOne) Ignore() *WalletUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WalletUpsertOne) DoNothing() *WalletUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WalletCreate.OnConflict
// documentation for more info.
func (u *WalletUpsertOne) Update(set func(*WalletUpsert)) *WalletUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WalletUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *WalletUpsertOne) SetUserID(v uuid.UUID) *WalletUpsertOne {
	return u.Update(func(s *WalletUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *WalletUpsertOne) UpdateUserID() *WalletUpsertOne {
	return u.Update(func(s *WalletUpsert) {
		s.UpdateUserID()
	})
}

// SetBalance sets the "balance" field.
func (u *WalletUpsertOne) SetBalance(v int64) *WalletUpsertOne {
	return u.Update(func(s *WalletUpsert) {
		s.SetBalance(v)
	})
}

// AddBalance adds v to the "balance" field.
func (u *WalletUpsertOne) AddBalance(v int64) *WalletUpsertOne {
	return u.Update(func(s *WalletUpsert) {
		s.AddBalance(v)
	})
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *WalletUpsertOne) UpdateBalance() *WalletUpsertOne {
	return u.Update(func(s *WalletUpsert) {
		s.UpdateBalance()
	})
}

// SetVersionNumber sets the "version_number" field.
func (u *WalletUpsertOne) SetVersionNumber(v int64) *WalletUpsertOne {
	return u.Update(func(s *WalletUpsert) {
		s.SetVersionNumber(v)
	})
}

// AddVersionNumber adds v to the "version_number" field.
func (u *WalletUpsertOne) AddVersionNumber(v int64) *WalletUpsertOne {
	return u.Update(func(s *WalletUpsert) {
		s.AddVersionNumber(v)
	})
}

// UpdateVersionNumber sets the "version_number" field to the value that was provided on create.
func (u *WalletUpsertOne) UpdateVersionNumber() *WalletUpsertOne {
	return u.Update(func(s *WalletUpsert) {
		s.UpdateVersionNumber()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WalletUpsertOne) SetUpdatedAt(v time.Time) *WalletUpsertOne {
	return u.Update(func(s *WalletUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WalletUpsertOne) UpdateUpdatedAt() *WalletUpsertOne {
	return u.Update(func(s *WalletUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *WalletUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WalletCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WalletUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *WalletUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *WalletUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// WalletCreateBulk is the builder for creating many Wallet entities in bulk.
type WalletCreateBulk struct {
	config
	err      error
	builders []*WalletCreate
	conflict []sql.ConflictOption
}

// Save creates the Wallet entities in the database.
func (_c *WalletCreateBulk) Save(ctx context.Context) ([]*Wallet, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Wallet, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WalletMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WalletCreateBulk) SaveX(ctx context.Context) []*Wallet {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WalletCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WalletCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Wallet.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WalletUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *WalletCreateBulk) OnConflict(opts ...sql.ConflictOption) *WalletUpsertBulk {
	_c.conflict = opts
	return &WalletUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Wallet.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WalletCreateBulk) OnConflictColumns(columns ...string) *WalletUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WalletUpsertBulk{
		create: _c,
	}
}

// WalletUpsertBulk is the builder for "upsert"-ing
// a bulk of Wallet nodes.
type WalletUpsertBulk struct {
	create *WalletCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Wallet.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WalletUpsertBulk) UpdateNewValues() *WalletUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(wallet.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Wallet.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *WalletUpsertBulk) Ignore() *WalletUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WalletUpsertBulk) DoNothing() *WalletUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WalletCreateBulk.OnConflict
// documentation for more info.
func (u *WalletUpsertBulk) Update(set func(*WalletUpsert)) *WalletUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WalletUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *WalletUpsertBulk) SetUserID(v uuid.UUID) *WalletUpsertBulk {
	return u.Update(func(s *WalletUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *WalletUpsertBulk) UpdateUserID() *WalletUpsertBulk {
	return u.Update(func(s *WalletUpsert) {
		s.UpdateUserID()
	})
}

// SetBalance sets the "balance" field.
func (u *WalletUpsertBulk) SetBalance(v int64) *WalletUpsertBulk {
	return u.Update(func(s *WalletUpsert) {
		s.SetBalance(v)
	})
}

// AddBalance adds v to the "balance" field.
func (u *WalletUpsertBulk) AddBalance(v int64) *WalletUpsertBulk {
	return u.Update(func(s *WalletUpsert) {
		s.AddBalance(v)
	})
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *WalletUpsertBulk) UpdateBalance() *WalletUpsertBulk {
	return u.Update(func(s *WalletUpsert) {
		s.UpdateBalance()
	})
}

// SetVersionNumber sets the "version_number" field.
func (u *WalletUpsertBulk) SetVersionNumber(v int64) *WalletUpsertBulk {
	return u.Update(func(s *WalletUpsert) {
		s.SetVersionNumber(v)
	})
}

// AddVersionNumber adds v to the "version_number" field.
func (u *WalletUpsertBulk) AddVersionNumber(v int64) *WalletUpsertBulk {
	return u.Update(func(s *WalletUpsert) {
		s.AddVersionNumber(v)
	})
}

// UpdateVersionNumber sets the "version_number" field to the value that was provided on create.
func (u *WalletUpsertBulk) UpdateVersionNumber() *WalletUpsertBulk {
	return u.Update(func(s *WalletUpsert) {
		s.UpdateVersionNumber()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WalletUpsertBulk) SetUpdatedAt(v time.Time) *WalletUpsertBulk {
	return u.Update(func(s *WalletUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WalletUpsertBulk) UpdateUpdatedAt() *WalletUpsertBulk {
	return u.Update(func(s *WalletUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *WalletUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the WalletCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WalletCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WalletUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
