// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: room/room.proto

package room

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoleType int32

const (
	RoleType_ROLE_OWNER         RoleType = 0 // 房间所有者：拥有全部权限
	RoleType_ROLE_ADMINISTRATOR RoleType = 1 // 管理员：可删除弹幕、禁言用户
	RoleType_ROLE_VIP           RoleType = 2 // 付费用户：可发送置顶弹幕
)

// Enum value maps for RoleType.
var (
	RoleType_name = map[int32]string{
		0: "ROLE_OWNER",
		1: "ROLE_ADMINISTRATOR",
		2: "ROLE_VIP",
	}
	RoleType_value = map[string]int32{
		"ROLE_OWNER":         0,
		"ROLE_ADMINISTRATOR": 1,
		"ROLE_VIP":           2,
	}
)

func (x RoleType) Enum() *RoleType {
	p := new(RoleType)
	*p = x
	return p
}

func (x RoleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoleType) Descriptor() protoreflect.EnumDescriptor {
	return file_room_room_proto_enumTypes[0].Descriptor()
}

func (RoleType) Type() protoreflect.EnumType {
	return &file_room_room_proto_enumTypes[0]
}

func (x RoleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoleType.Descriptor instead.
func (RoleType) EnumDescriptor() ([]byte, []int) {
	return file_room_room_proto_rawDescGZIP(), []int{0}
}

type Permission int32

const (
	Permission_PERMISSION_UNSPECIFIED    Permission = 0
	Permission_PERMISSION_DANMAKU_SEND   Permission = 1
	Permission_PERMISSION_DANMAKU_PIN    Permission = 2
	Permission_PERMISSION_DANMAKU_DELETE Permission = 3
	Permission_PERMISSION_USER_MANAGE    Permission = 4
	Permission_PERMISSION_ROLE_MANAGE    Permission = 5
)

// Enum value maps for Permission.
var (
	Permission_name = map[int32]string{
		0: "PERMISSION_UNSPECIFIED",
		1: "PERMISSION_DANMAKU_SEND",
		2: "PERMISSION_DANMAKU_PIN",
		3: "PERMISSION_DANMAKU_DELETE",
		4: "PERMISSION_USER_MANAGE",
		5: "PERMISSION_ROLE_MANAGE",
	}
	Permission_value = map[string]int32{
		"PERMISSION_UNSPECIFIED":    0,
		"PERMISSION_DANMAKU_SEND":   1,
		"PERMISSION_DANMAKU_PIN":    2,
		"PERMISSION_DANMAKU_DELETE": 3,
		"PERMISSION_USER_MANAGE":    4,
		"PERMISSION_ROLE_MANAGE":    5,
	}
)

func (x Permission) Enum() *Permission {
	p := new(Permission)
	*p = x
	return p
}

func (x Permission) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Permission) Descriptor() protoreflect.EnumDescriptor {
	return file_room_room_proto_enumTypes[1].Descriptor()
}

func (Permission) Type() protoreflect.EnumType {
	return &file_room_room_proto_enumTypes[1]
}

func (x Permission) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Permission.Descriptor instead.
func (Permission) EnumDescriptor() ([]byte, []int) {
	return file_room_room_proto_rawDescGZIP(), []int{1}
}

type Room struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IsActive      bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_room_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_room_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_room_room_proto_rawDescGZIP(), []int{0}
}

func (x *Room) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Room) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Room) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Room) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Room) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Room) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Room) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type UserRoomRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Role          RoleType               `protobuf:"varint,3,opt,name=role,proto3,enum=room.RoleType" json:"role,omitempty"`                        // 角色类型（对应权限由后端推导）
	Permissions   []Permission           `protobuf:"varint,4,rep,packed,name=permissions,proto3,enum=room.Permission" json:"permissions,omitempty"` // 权限列表（由后端根据角色自动生成）
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRoomRole) Reset() {
	*x = UserRoomRole{}
	mi := &file_room_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRoomRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRoomRole) ProtoMessage() {}

func (x *UserRoomRole) ProtoReflect() protoreflect.Message {
	mi := &file_room_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRoomRole.ProtoReflect.Descriptor instead.
func (*UserRoomRole) Descriptor() ([]byte, []int) {
	return file_room_room_proto_rawDescGZIP(), []int{1}
}

func (x *UserRoomRole) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserRoomRole) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *UserRoomRole) GetRole() RoleType {
	if x != nil {
		return x.Role
	}
	return RoleType_ROLE_OWNER
}

func (x *UserRoomRole) GetPermissions() []Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *UserRoomRole) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *UserRoomRole) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

var File_room_room_proto protoreflect.FileDescriptor

const file_room_room_proto_rawDesc = "" +
	"\n" +
	"\x0froom/room.proto\x12\x04room\"\xcd\x01\n" +
	"\x04Room\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\"\xd6\x01\n" +
	"\fUserRoomRole\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\"\n" +
	"\x04role\x18\x03 \x01(\x0e2\x0e.room.RoleTypeR\x04role\x122\n" +
	"\vpermissions\x18\x04 \x03(\x0e2\x10.room.PermissionR\vpermissions\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt*@\n" +
	"\bRoleType\x12\x0e\n" +
	"\n" +
	"ROLE_OWNER\x10\x00\x12\x16\n" +
	"\x12ROLE_ADMINISTRATOR\x10\x01\x12\f\n" +
	"\bROLE_VIP\x10\x02*\xb8\x01\n" +
	"\n" +
	"Permission\x12\x1a\n" +
	"\x16PERMISSION_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17PERMISSION_DANMAKU_SEND\x10\x01\x12\x1a\n" +
	"\x16PERMISSION_DANMAKU_PIN\x10\x02\x12\x1d\n" +
	"\x19PERMISSION_DANMAKU_DELETE\x10\x03\x12\x1a\n" +
	"\x16PERMISSION_USER_MANAGE\x10\x04\x12\x1a\n" +
	"\x16PERMISSION_ROLE_MANAGE\x10\x05B\x18Z\x16shared/proto/room;roomb\x06proto3"

var (
	file_room_room_proto_rawDescOnce sync.Once
	file_room_room_proto_rawDescData []byte
)

func file_room_room_proto_rawDescGZIP() []byte {
	file_room_room_proto_rawDescOnce.Do(func() {
		file_room_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_room_room_proto_rawDesc), len(file_room_room_proto_rawDesc)))
	})
	return file_room_room_proto_rawDescData
}

var file_room_room_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_room_room_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_room_room_proto_goTypes = []any{
	(RoleType)(0),        // 0: room.RoleType
	(Permission)(0),      // 1: room.Permission
	(*Room)(nil),         // 2: room.Room
	(*UserRoomRole)(nil), // 3: room.UserRoomRole
}
var file_room_room_proto_depIdxs = []int32{
	0, // 0: room.UserRoomRole.role:type_name -> room.RoleType
	1, // 1: room.UserRoomRole.permissions:type_name -> room.Permission
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_room_room_proto_init() }
func file_room_room_proto_init() {
	if File_room_room_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_room_room_proto_rawDesc), len(file_room_room_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_room_room_proto_goTypes,
		DependencyIndexes: file_room_room_proto_depIdxs,
		EnumInfos:         file_room_room_proto_enumTypes,
		MessageInfos:      file_room_room_proto_msgTypes,
	}.Build()
	File_room_room_proto = out.File
	file_room_room_proto_goTypes = nil
	file_room_room_proto_depIdxs = nil
}
