// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// GiftsColumns holds the columns for the "gifts" table.
	GiftsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 50},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 200},
		{Name: "icon_url", Type: field.TypeString, Nullable: true, Size: 500},
		{Name: "cache_key", Type: field.TypeString},
		{Name: "price", Type: field.TypeInt64},
		{Name: "vip_only", Type: field.TypeBool, Default: false},
		{Name: "special_effect", Type: field.TypeString, Nullable: true, Size: 50},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"online", "offline", "limited_time"}, Default: "online"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// GiftsTable holds the schema information for the "gifts" table.
	GiftsTable = &schema.Table{
		Name:       "gifts",
		Columns:    GiftsColumns,
		PrimaryKey: []*schema.Column{GiftsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "gift_cache_key",
				Unique:  true,
				Columns: []*schema.Column{GiftsColumns[4]},
			},
			{
				Name:    "gift_status",
				Unique:  false,
				Columns: []*schema.Column{GiftsColumns[8]},
			},
			{
				Name:    "gift_price",
				Unique:  false,
				Columns: []*schema.Column{GiftsColumns[5]},
			},
			{
				Name:    "gift_created_at",
				Unique:  false,
				Columns: []*schema.Column{GiftsColumns[9]},
			},
		},
	}
	// GiftRecordsColumns holds the columns for the "gift_records" table.
	GiftRecordsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "idempotency_key", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "anchor_id", Type: field.TypeUUID},
		{Name: "room_id", Type: field.TypeUUID},
		{Name: "gift_id", Type: field.TypeInt64},
		{Name: "amount", Type: field.TypeInt64},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "success", "failed"}, Default: "pending"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// GiftRecordsTable holds the schema information for the "gift_records" table.
	GiftRecordsTable = &schema.Table{
		Name:       "gift_records",
		Columns:    GiftRecordsColumns,
		PrimaryKey: []*schema.Column{GiftRecordsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "giftrecord_idempotency_key",
				Unique:  true,
				Columns: []*schema.Column{GiftRecordsColumns[1]},
			},
			{
				Name:    "giftrecord_user_id",
				Unique:  false,
				Columns: []*schema.Column{GiftRecordsColumns[2]},
			},
			{
				Name:    "giftrecord_anchor_id",
				Unique:  false,
				Columns: []*schema.Column{GiftRecordsColumns[3]},
			},
			{
				Name:    "giftrecord_room_id",
				Unique:  false,
				Columns: []*schema.Column{GiftRecordsColumns[4]},
			},
			{
				Name:    "giftrecord_status",
				Unique:  false,
				Columns: []*schema.Column{GiftRecordsColumns[7]},
			},
			{
				Name:    "giftrecord_created_at",
				Unique:  false,
				Columns: []*schema.Column{GiftRecordsColumns[8]},
			},
			{
				Name:    "giftrecord_status_created_at",
				Unique:  false,
				Columns: []*schema.Column{GiftRecordsColumns[7], GiftRecordsColumns[8]},
			},
		},
	}
	// WalletsColumns holds the columns for the "wallets" table.
	WalletsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "balance", Type: field.TypeInt64, Default: 0},
		{Name: "version_number", Type: field.TypeInt64, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// WalletsTable holds the schema information for the "wallets" table.
	WalletsTable = &schema.Table{
		Name:       "wallets",
		Columns:    WalletsColumns,
		PrimaryKey: []*schema.Column{WalletsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "wallet_user_id",
				Unique:  true,
				Columns: []*schema.Column{WalletsColumns[1]},
			},
			{
				Name:    "wallet_updated_at",
				Unique:  false,
				Columns: []*schema.Column{WalletsColumns[5]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		GiftsTable,
		GiftRecordsTable,
		WalletsTable,
	}
)

func init() {
}
