// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"live-interact-engine/services/room-service/ent/mute"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// MuteCreate is the builder for creating a Mute entity.
type MuteCreate struct {
	config
	mutation *MuteMutation
	hooks    []Hook
}

// SetRoomID sets the "room_id" field.
func (_c *MuteCreate) SetRoomID(v uuid.UUID) *MuteCreate {
	_c.mutation.SetRoomID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *MuteCreate) SetUserID(v uuid.UUID) *MuteCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAdminID sets the "admin_id" field.
func (_c *MuteCreate) SetAdminID(v uuid.UUID) *MuteCreate {
	_c.mutation.SetAdminID(v)
	return _c
}

// SetReason sets the "reason" field.
func (_c *MuteCreate) SetReason(v string) *MuteCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *MuteCreate) SetNillableReason(v *string) *MuteCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetDuration sets the "duration" field.
func (_c *MuteCreate) SetDuration(v int64) *MuteCreate {
	_c.mutation.SetDuration(v)
	return _c
}

// SetMutedAt sets the "muted_at" field.
func (_c *MuteCreate) SetMutedAt(v int64) *MuteCreate {
	_c.mutation.SetMutedAt(v)
	return _c
}

// SetNillableMutedAt sets the "muted_at" field if the given value is not nil.
func (_c *MuteCreate) SetNillableMutedAt(v *int64) *MuteCreate {
	if v != nil {
		_c.SetMutedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *MuteCreate) SetExpiresAt(v int64) *MuteCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *MuteCreate) SetNillableExpiresAt(v *int64) *MuteCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MuteCreate) SetCreatedAt(v int64) *MuteCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MuteCreate) SetNillableCreatedAt(v *int64) *MuteCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MuteCreate) SetUpdatedAt(v int64) *MuteCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MuteCreate) SetNillableUpdatedAt(v *int64) *MuteCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MuteCreate) SetID(v uuid.UUID) *MuteCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *MuteCreate) SetNillableID(v *uuid.UUID) *MuteCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the MuteMutation object of the builder.
func (_c *MuteCreate) Mutation() *MuteMutation {
	return _c.mutation
}

// Save creates the Mute in the database.
func (_c *MuteCreate) Save(ctx context.Context) (*Mute, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MuteCreate) SaveX(ctx context.Context) *Mute {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MuteCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MuteCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MuteCreate) defaults() {
	if _, ok := _c.mutation.MutedAt(); !ok {
		v := mute.DefaultMutedAt()
		_c.mutation.SetMutedAt(v)
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		v := mute.DefaultExpiresAt()
		_c.mutation.SetExpiresAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := mute.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := mute.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := mute.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MuteCreate) check() error {
	if _, ok := _c.mutation.RoomID(); !ok {
		return &ValidationError{Name: "room_id", err: errors.New(`ent: missing required field "Mute.room_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Mute.user_id"`)}
	}
	if _, ok := _c.mutation.AdminID(); !ok {
		return &ValidationError{Name: "admin_id", err: errors.New(`ent: missing required field "Mute.admin_id"`)}
	}
	if _, ok := _c.mutation.Duration(); !ok {
		return &ValidationError{Name: "duration", err: errors.New(`ent: missing required field "Mute.duration"`)}
	}
	if _, ok := _c.mutation.MutedAt(); !ok {
		return &ValidationError{Name: "muted_at", err: errors.New(`ent: missing required field "Mute.muted_at"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "Mute.expires_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Mute.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Mute.updated_at"`)}
	}
	return nil
}

func (_c *MuteCreate) sqlSave(ctx context.Context) (*Mute, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MuteCreate) createSpec() (*Mute, *sqlgraph.CreateSpec) {
	var (
		_node = &Mute{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mute.Table, sqlgraph.NewFieldSpec(mute.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.RoomID(); ok {
		_spec.SetField(mute.FieldRoomID, field.TypeUUID, value)
		_node.RoomID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(mute.FieldUserID, field.TypeUUID, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.AdminID(); ok {
		_spec.SetField(mute.FieldAdminID, field.TypeUUID, value)
		_node.AdminID = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(mute.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := _c.mutation.Duration(); ok {
		_spec.SetField(mute.FieldDuration, field.TypeInt64, value)
		_node.Duration = value
	}
	if value, ok := _c.mutation.MutedAt(); ok {
		_spec.SetField(mute.FieldMutedAt, field.TypeInt64, value)
		_node.MutedAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(mute.FieldExpiresAt, field.TypeInt64, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(mute.FieldCreatedAt, field.TypeInt64, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(mute.FieldUpdatedAt, field.TypeInt64, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// MuteCreateBulk is the builder for creating many Mute entities in bulk.
type MuteCreateBulk struct {
	config
	err      error
	builders []*MuteCreate
}

// Save creates the Mute entities in the database.
func (_c *MuteCreateBulk) Save(ctx context.Context) ([]*Mute, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Mute, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MuteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MuteCreateBulk) SaveX(ctx context.Context) []*Mute {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MuteCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MuteCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
