// Code generated by ent, DO NOT EDIT.

package ent

import (
	"live-interact-engine/services/room-service/ent/room"
	"live-interact-engine/services/room-service/ent/schema"
	"live-interact-engine/services/room-service/ent/userroomrole"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	roomFields := schema.Room{}.Fields()
	_ = roomFields
	// roomDescTitle is the schema descriptor for title field.
	roomDescTitle := roomFields[2].Descriptor()
	// room.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	room.TitleValidator = func() func(string) error {
		validators := roomDescTitle.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
			validators[2].(func(string) error),
		}
		return func(title string) error {
			for _, fn := range fns {
				if err := fn(title); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// roomDescCreatedAt is the schema descriptor for created_at field.
	roomDescCreatedAt := roomFields[4].Descriptor()
	// room.DefaultCreatedAt holds the default value on creation for the created_at field.
	room.DefaultCreatedAt = roomDescCreatedAt.Default.(func() int64)
	// roomDescUpdatedAt is the schema descriptor for updated_at field.
	roomDescUpdatedAt := roomFields[5].Descriptor()
	// room.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	room.DefaultUpdatedAt = roomDescUpdatedAt.Default.(func() int64)
	// room.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	room.UpdateDefaultUpdatedAt = roomDescUpdatedAt.UpdateDefault.(func() int64)
	// roomDescIsActive is the schema descriptor for is_active field.
	roomDescIsActive := roomFields[6].Descriptor()
	// room.DefaultIsActive holds the default value on creation for the is_active field.
	room.DefaultIsActive = roomDescIsActive.Default.(bool)
	// roomDescID is the schema descriptor for id field.
	roomDescID := roomFields[0].Descriptor()
	// room.DefaultID holds the default value on creation for the id field.
	room.DefaultID = roomDescID.Default.(func() uuid.UUID)
	userroomroleFields := schema.UserRoomRole{}.Fields()
	_ = userroomroleFields
	// userroomroleDescRoleName is the schema descriptor for role_name field.
	userroomroleDescRoleName := userroomroleFields[2].Descriptor()
	// userroomrole.RoleNameValidator is a validator for the "role_name" field. It is called by the builders before save.
	userroomrole.RoleNameValidator = func() func(string) error {
		validators := userroomroleDescRoleName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(role_name string) error {
			for _, fn := range fns {
				if err := fn(role_name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userroomroleDescPermissions is the schema descriptor for permissions field.
	userroomroleDescPermissions := userroomroleFields[3].Descriptor()
	// userroomrole.DefaultPermissions holds the default value on creation for the permissions field.
	userroomrole.DefaultPermissions = userroomroleDescPermissions.Default.([]int32)
	// userroomroleDescCreatedAt is the schema descriptor for created_at field.
	userroomroleDescCreatedAt := userroomroleFields[4].Descriptor()
	// userroomrole.DefaultCreatedAt holds the default value on creation for the created_at field.
	userroomrole.DefaultCreatedAt = userroomroleDescCreatedAt.Default.(func() int64)
	// userroomroleDescUpdatedAt is the schema descriptor for updated_at field.
	userroomroleDescUpdatedAt := userroomroleFields[5].Descriptor()
	// userroomrole.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	userroomrole.DefaultUpdatedAt = userroomroleDescUpdatedAt.Default.(func() int64)
	// userroomrole.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	userroomrole.UpdateDefaultUpdatedAt = userroomroleDescUpdatedAt.UpdateDefault.(func() int64)
}
