// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"live-interact-engine/services/room-service/ent/room"
	"live-interact-engine/services/room-service/ent/userroomrole"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// UserRoomRole is the model entity for the UserRoomRole schema.
type UserRoomRole struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// RoomID holds the value of the "room_id" field.
	RoomID uuid.UUID `json:"room_id,omitempty"`
	// RoleName holds the value of the "role_name" field.
	RoleName string `json:"role_name,omitempty"`
	// Permissions holds the value of the "permissions" field.
	Permissions []int32 `json:"permissions,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt int64 `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt int64 `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserRoomRoleQuery when eager-loading is set.
	Edges        UserRoomRoleEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserRoomRoleEdges holds the relations/edges for other nodes in the graph.
type UserRoomRoleEdges struct {
	// Room holds the value of the room edge.
	Room *Room `json:"room,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RoomOrErr returns the Room value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserRoomRoleEdges) RoomOrErr() (*Room, error) {
	if e.Room != nil {
		return e.Room, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: room.Label}
	}
	return nil, &NotLoadedError{edge: "room"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserRoomRole) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userroomrole.FieldPermissions:
			values[i] = new([]byte)
		case userroomrole.FieldID, userroomrole.FieldCreatedAt, userroomrole.FieldUpdatedAt:
			values[i] = new(sql.NullInt64)
		case userroomrole.FieldRoleName:
			values[i] = new(sql.NullString)
		case userroomrole.FieldUserID, userroomrole.FieldRoomID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserRoomRole fields.
func (_m *UserRoomRole) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userroomrole.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case userroomrole.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case userroomrole.FieldRoomID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field room_id", values[i])
			} else if value != nil {
				_m.RoomID = *value
			}
		case userroomrole.FieldRoleName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role_name", values[i])
			} else if value.Valid {
				_m.RoleName = value.String
			}
		case userroomrole.FieldPermissions:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field permissions", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Permissions); err != nil {
					return fmt.Errorf("unmarshal field permissions: %w", err)
				}
			}
		case userroomrole.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Int64
			}
		case userroomrole.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserRoomRole.
// This includes values selected through modifiers, order, etc.
func (_m *UserRoomRole) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRoom queries the "room" edge of the UserRoomRole entity.
func (_m *UserRoomRole) QueryRoom() *RoomQuery {
	return NewUserRoomRoleClient(_m.config).QueryRoom(_m)
}

// Update returns a builder for updating this UserRoomRole.
// Note that you need to call UserRoomRole.Unwrap() before calling this method if this UserRoomRole
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserRoomRole) Update() *UserRoomRoleUpdateOne {
	return NewUserRoomRoleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserRoomRole entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserRoomRole) Unwrap() *UserRoomRole {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserRoomRole is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserRoomRole) String() string {
	var builder strings.Builder
	builder.WriteString("UserRoomRole(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("room_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RoomID))
	builder.WriteString(", ")
	builder.WriteString("role_name=")
	builder.WriteString(_m.RoleName)
	builder.WriteString(", ")
	builder.WriteString("permissions=")
	builder.WriteString(fmt.Sprintf("%v", _m.Permissions))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedAt))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdatedAt))
	builder.WriteByte(')')
	return builder.String()
}

// UserRoomRoles is a parsable slice of UserRoomRole.
type UserRoomRoles []*UserRoomRole
