// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"live-interact-engine/services/room-service/ent/room"
	"live-interact-engine/services/room-service/ent/userroomrole"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UserRoomRoleCreate is the builder for creating a UserRoomRole entity.
type UserRoomRoleCreate struct {
	config
	mutation *UserRoomRoleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *UserRoomRoleCreate) SetUserID(v uuid.UUID) *UserRoomRoleCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetRoomID sets the "room_id" field.
func (_c *UserRoomRoleCreate) SetRoomID(v uuid.UUID) *UserRoomRoleCreate {
	_c.mutation.SetRoomID(v)
	return _c
}

// SetRoleName sets the "role_name" field.
func (_c *UserRoomRoleCreate) SetRoleName(v string) *UserRoomRoleCreate {
	_c.mutation.SetRoleName(v)
	return _c
}

// SetPermissions sets the "permissions" field.
func (_c *UserRoomRoleCreate) SetPermissions(v []int32) *UserRoomRoleCreate {
	_c.mutation.SetPermissions(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserRoomRoleCreate) SetCreatedAt(v int64) *UserRoomRoleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserRoomRoleCreate) SetNillableCreatedAt(v *int64) *UserRoomRoleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserRoomRoleCreate) SetUpdatedAt(v int64) *UserRoomRoleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserRoomRoleCreate) SetNillableUpdatedAt(v *int64) *UserRoomRoleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetRoom sets the "room" edge to the Room entity.
func (_c *UserRoomRoleCreate) SetRoom(v *Room) *UserRoomRoleCreate {
	return _c.SetRoomID(v.ID)
}

// Mutation returns the UserRoomRoleMutation object of the builder.
func (_c *UserRoomRoleCreate) Mutation() *UserRoomRoleMutation {
	return _c.mutation
}

// Save creates the UserRoomRole in the database.
func (_c *UserRoomRoleCreate) Save(ctx context.Context) (*UserRoomRole, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserRoomRoleCreate) SaveX(ctx context.Context) *UserRoomRole {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserRoomRoleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserRoomRoleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserRoomRoleCreate) defaults() {
	if _, ok := _c.mutation.Permissions(); !ok {
		v := userroomrole.DefaultPermissions
		_c.mutation.SetPermissions(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userroomrole.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := userroomrole.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserRoomRoleCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserRoomRole.user_id"`)}
	}
	if _, ok := _c.mutation.RoomID(); !ok {
		return &ValidationError{Name: "room_id", err: errors.New(`ent: missing required field "UserRoomRole.room_id"`)}
	}
	if _, ok := _c.mutation.RoleName(); !ok {
		return &ValidationError{Name: "role_name", err: errors.New(`ent: missing required field "UserRoomRole.role_name"`)}
	}
	if v, ok := _c.mutation.RoleName(); ok {
		if err := userroomrole.RoleNameValidator(v); err != nil {
			return &ValidationError{Name: "role_name", err: fmt.Errorf(`ent: validator failed for field "UserRoomRole.role_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Permissions(); !ok {
		return &ValidationError{Name: "permissions", err: errors.New(`ent: missing required field "UserRoomRole.permissions"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserRoomRole.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserRoomRole.updated_at"`)}
	}
	if len(_c.mutation.RoomIDs()) == 0 {
		return &ValidationError{Name: "room", err: errors.New(`ent: missing required edge "UserRoomRole.room"`)}
	}
	return nil
}

func (_c *UserRoomRoleCreate) sqlSave(ctx context.Context) (*UserRoomRole, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserRoomRoleCreate) createSpec() (*UserRoomRole, *sqlgraph.CreateSpec) {
	var (
		_node = &UserRoomRole{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userroomrole.Table, sqlgraph.NewFieldSpec(userroomrole.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(userroomrole.FieldUserID, field.TypeUUID, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.RoleName(); ok {
		_spec.SetField(userroomrole.FieldRoleName, field.TypeString, value)
		_node.RoleName = value
	}
	if value, ok := _c.mutation.Permissions(); ok {
		_spec.SetField(userroomrole.FieldPermissions, field.TypeJSON, value)
		_node.Permissions = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userroomrole.FieldCreatedAt, field.TypeInt64, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(userroomrole.FieldUpdatedAt, field.TypeInt64, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.RoomIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userroomrole.RoomTable,
			Columns: []string{userroomrole.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RoomID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserRoomRole.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserRoomRoleUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserRoomRoleCreate) OnConflict(opts ...sql.ConflictOption) *UserRoomRoleUpsertOne {
	_c.conflict = opts
	return &UserRoomRoleUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserRoomRole.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserRoomRoleCreate) OnConflictColumns(columns ...string) *UserRoomRoleUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserRoomRoleUpsertOne{
		create: _c,
	}
}

type (
	// UserRoomRoleUpsertOne is the builder for "upsert"-ing
	//  one UserRoomRole node.
	UserRoomRoleUpsertOne struct {
		create *UserRoomRoleCreate
	}

	// UserRoomRoleUpsert is the "OnConflict" setter.
	UserRoomRoleUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *UserRoomRoleUpsert) SetUserID(v uuid.UUID) *UserRoomRoleUpsert {
	u.Set(userroomrole.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserRoomRoleUpsert) UpdateUserID() *UserRoomRoleUpsert {
	u.SetExcluded(userroomrole.FieldUserID)
	return u
}

// SetRoomID sets the "room_id" field.
func (u *UserRoomRoleUpsert) SetRoomID(v uuid.UUID) *UserRoomRoleUpsert {
	u.Set(userroomrole.FieldRoomID, v)
	return u
}

// UpdateRoomID sets the "room_id" field to the value that was provided on create.
func (u *UserRoomRoleUpsert) UpdateRoomID() *UserRoomRoleUpsert {
	u.SetExcluded(userroomrole.FieldRoomID)
	return u
}

// SetRoleName sets the "role_name" field.
func (u *UserRoomRoleUpsert) SetRoleName(v string) *UserRoomRoleUpsert {
	u.Set(userroomrole.FieldRoleName, v)
	return u
}

// UpdateRoleName sets the "role_name" field to the value that was provided on create.
func (u *UserRoomRoleUpsert) UpdateRoleName() *UserRoomRoleUpsert {
	u.SetExcluded(userroomrole.FieldRoleName)
	return u
}

// SetPermissions sets the "permissions" field.
func (u *UserRoomRoleUpsert) SetPermissions(v []int32) *UserRoomRoleUpsert {
	u.Set(userroomrole.FieldPermissions, v)
	return u
}

// UpdatePermissions sets the "permissions" field to the value that was provided on create.
func (u *UserRoomRoleUpsert) UpdatePermissions() *UserRoomRoleUpsert {
	u.SetExcluded(userroomrole.FieldPermissions)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserRoomRoleUpsert) SetUpdatedAt(v int64) *UserRoomRoleUpsert {
	u.Set(userroomrole.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserRoomRoleUpsert) UpdateUpdatedAt() *UserRoomRoleUpsert {
	u.SetExcluded(userroomrole.FieldUpdatedAt)
	return u
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *UserRoomRoleUpsert) AddUpdatedAt(v int64) *UserRoomRoleUpsert {
	u.Add(userroomrole.FieldUpdatedAt, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserRoomRole.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserRoomRoleUpsertOne) UpdateNewValues() *UserRoomRoleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(userroomrole.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserRoomRole.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserRoomRoleUpsertOne) Ignore() *UserRoomRoleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserRoomRoleUpsertOne) DoNothing() *UserRoomRoleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserRoomRoleCreate.OnConflict
// documentation for more info.
func (u *UserRoomRoleUpsertOne) Update(set func(*UserRoomRoleUpsert)) *UserRoomRoleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserRoomRoleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserRoomRoleUpsertOne) SetUserID(v uuid.UUID) *UserRoomRoleUpsertOne {
	return u.Update(func(s *UserRoomRoleUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserRoomRoleUpsertOne) UpdateUserID() *UserRoomRoleUpsertOne {
	return u.Update(func(s *UserRoomRoleUpsert) {
		s.UpdateUserID()
	})
}

// SetRoomID sets the "room_id" field.
func (u *UserRoomRoleUpsertOne) SetRoomID(v uuid.UUID) *UserRoomRoleUpsertOne {
	return u.Update(func(s *UserRoomRoleUpsert) {
		s.SetRoomID(v)
	})
}

// UpdateRoomID sets the "room_id" field to the value that was provided on create.
func (u *UserRoomRoleUpsertOne) UpdateRoomID() *UserRoomRoleUpsertOne {
	return u.Update(func(s *UserRoomRoleUpsert) {
		s.UpdateRoomID()
	})
}

// SetRoleName sets the "role_name" field.
func (u *UserRoomRoleUpsertOne) SetRoleName(v string) *UserRoomRoleUpsertOne {
	return u.Update(func(s *UserRoomRoleUpsert) {
		s.SetRoleName(v)
	})
}

// UpdateRoleName sets the "role_name" field to the value that was provided on create.
func (u *UserRoomRoleUpsertOne) UpdateRoleName() *UserRoomRoleUpsertOne {
	return u.Update(func(s *UserRoomRoleUpsert) {
		s.UpdateRoleName()
	})
}

// SetPermissions sets the "permissions" field.
func (u *UserRoomRoleUpsertOne) SetPermissions(v []int32) *UserRoomRoleUpsertOne {
	return u.Update(func(s *UserRoomRoleUpsert) {
		s.SetPermissions(v)
	})
}

// UpdatePermissions sets the "permissions" field to the value that was provided on create.
func (u *UserRoomRoleUpsertOne) UpdatePermissions() *UserRoomRoleUpsertOne {
	return u.Update(func(s *UserRoomRoleUpsert) {
		s.UpdatePermissions()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserRoomRoleUpsertOne) SetUpdatedAt(v int64) *UserRoomRoleUpsertOne {
	return u.Update(func(s *UserRoomRoleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *UserRoomRoleUpsertOne) AddUpdatedAt(v int64) *UserRoomRoleUpsertOne {
	return u.Update(func(s *UserRoomRoleUpsert) {
		s.AddUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserRoomRoleUpsertOne) UpdateUpdatedAt() *UserRoomRoleUpsertOne {
	return u.Update(func(s *UserRoomRoleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserRoomRoleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserRoomRoleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserRoomRoleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserRoomRoleUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserRoomRoleUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserRoomRoleCreateBulk is the builder for creating many UserRoomRole entities in bulk.
type UserRoomRoleCreateBulk struct {
	config
	err      error
	builders []*UserRoomRoleCreate
	conflict []sql.ConflictOption
}

// Save creates the UserRoomRole entities in the database.
func (_c *UserRoomRoleCreateBulk) Save(ctx context.Context) ([]*UserRoomRole, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserRoomRole, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserRoomRoleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserRoomRoleCreateBulk) SaveX(ctx context.Context) []*UserRoomRole {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserRoomRoleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserRoomRoleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserRoomRole.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserRoomRoleUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserRoomRoleCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserRoomRoleUpsertBulk {
	_c.conflict = opts
	return &UserRoomRoleUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserRoomRole.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserRoomRoleCreateBulk) OnConflictColumns(columns ...string) *UserRoomRoleUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserRoomRoleUpsertBulk{
		create: _c,
	}
}

// UserRoomRoleUpsertBulk is the builder for "upsert"-ing
// a bulk of UserRoomRole nodes.
type UserRoomRoleUpsertBulk struct {
	create *UserRoomRoleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserRoomRole.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserRoomRoleUpsertBulk) UpdateNewValues() *UserRoomRoleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(userroomrole.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserRoomRole.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserRoomRoleUpsertBulk) Ignore() *UserRoomRoleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserRoomRoleUpsertBulk) DoNothing() *UserRoomRoleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserRoomRoleCreateBulk.OnConflict
// documentation for more info.
func (u *UserRoomRoleUpsertBulk) Update(set func(*UserRoomRoleUpsert)) *UserRoomRoleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserRoomRoleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserRoomRoleUpsertBulk) SetUserID(v uuid.UUID) *UserRoomRoleUpsertBulk {
	return u.Update(func(s *UserRoomRoleUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserRoomRoleUpsertBulk) UpdateUserID() *UserRoomRoleUpsertBulk {
	return u.Update(func(s *UserRoomRoleUpsert) {
		s.UpdateUserID()
	})
}

// SetRoomID sets the "room_id" field.
func (u *UserRoomRoleUpsertBulk) SetRoomID(v uuid.UUID) *UserRoomRoleUpsertBulk {
	return u.Update(func(s *UserRoomRoleUpsert) {
		s.SetRoomID(v)
	})
}

// UpdateRoomID sets the "room_id" field to the value that was provided on create.
func (u *UserRoomRoleUpsertBulk) UpdateRoomID() *UserRoomRoleUpsertBulk {
	return u.Update(func(s *UserRoomRoleUpsert) {
		s.UpdateRoomID()
	})
}

// SetRoleName sets the "role_name" field.
func (u *UserRoomRoleUpsertBulk) SetRoleName(v string) *UserRoomRoleUpsertBulk {
	return u.Update(func(s *UserRoomRoleUpsert) {
		s.SetRoleName(v)
	})
}

// UpdateRoleName sets the "role_name" field to the value that was provided on create.
func (u *UserRoomRoleUpsertBulk) UpdateRoleName() *UserRoomRoleUpsertBulk {
	return u.Update(func(s *UserRoomRoleUpsert) {
		s.UpdateRoleName()
	})
}

// SetPermissions sets the "permissions" field.
func (u *UserRoomRoleUpsertBulk) SetPermissions(v []int32) *UserRoomRoleUpsertBulk {
	return u.Update(func(s *UserRoomRoleUpsert) {
		s.SetPermissions(v)
	})
}

// UpdatePermissions sets the "permissions" field to the value that was provided on create.
func (u *UserRoomRoleUpsertBulk) UpdatePermissions() *UserRoomRoleUpsertBulk {
	return u.Update(func(s *UserRoomRoleUpsert) {
		s.UpdatePermissions()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserRoomRoleUpsertBulk) SetUpdatedAt(v int64) *UserRoomRoleUpsertBulk {
	return u.Update(func(s *UserRoomRoleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *UserRoomRoleUpsertBulk) AddUpdatedAt(v int64) *UserRoomRoleUpsertBulk {
	return u.Update(func(s *UserRoomRoleUpsert) {
		s.AddUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserRoomRoleUpsertBulk) UpdateUpdatedAt() *UserRoomRoleUpsertBulk {
	return u.Update(func(s *UserRoomRoleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserRoomRoleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserRoomRoleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserRoomRoleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserRoomRoleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
