// Code generated by ent, DO NOT EDIT.

package giftrecord

import (
	"live-interact-engine/services/gift-service/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldLTE(FieldID, id))
}

// IdempotencyKey applies equality check predicate on the "idempotency_key" field. It's identical to IdempotencyKeyEQ.
func IdempotencyKey(v string) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldEQ(FieldIdempotencyKey, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldEQ(FieldUserID, v))
}

// AnchorID applies equality check predicate on the "anchor_id" field. It's identical to AnchorIDEQ.
func AnchorID(v int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldEQ(FieldAnchorID, v))
}

// RoomID applies equality check predicate on the "room_id" field. It's identical to RoomIDEQ.
func RoomID(v int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldEQ(FieldRoomID, v))
}

// GiftID applies equality check predicate on the "gift_id" field. It's identical to GiftIDEQ.
func GiftID(v int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldEQ(FieldGiftID, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldEQ(FieldAmount, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldEQ(FieldUpdatedAt, v))
}

// IdempotencyKeyEQ applies the EQ predicate on the "idempotency_key" field.
func IdempotencyKeyEQ(v string) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyNEQ applies the NEQ predicate on the "idempotency_key" field.
func IdempotencyKeyNEQ(v string) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldNEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyIn applies the In predicate on the "idempotency_key" field.
func IdempotencyKeyIn(vs ...string) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyNotIn applies the NotIn predicate on the "idempotency_key" field.
func IdempotencyKeyNotIn(vs ...string) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldNotIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyGT applies the GT predicate on the "idempotency_key" field.
func IdempotencyKeyGT(v string) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldGT(FieldIdempotencyKey, v))
}

// IdempotencyKeyGTE applies the GTE predicate on the "idempotency_key" field.
func IdempotencyKeyGTE(v string) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldGTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyLT applies the LT predicate on the "idempotency_key" field.
func IdempotencyKeyLT(v string) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldLT(FieldIdempotencyKey, v))
}

// IdempotencyKeyLTE applies the LTE predicate on the "idempotency_key" field.
func IdempotencyKeyLTE(v string) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldLTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyContains applies the Contains predicate on the "idempotency_key" field.
func IdempotencyKeyContains(v string) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldContains(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasPrefix applies the HasPrefix predicate on the "idempotency_key" field.
func IdempotencyKeyHasPrefix(v string) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldHasPrefix(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasSuffix applies the HasSuffix predicate on the "idempotency_key" field.
func IdempotencyKeyHasSuffix(v string) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldHasSuffix(FieldIdempotencyKey, v))
}

// IdempotencyKeyEqualFold applies the EqualFold predicate on the "idempotency_key" field.
func IdempotencyKeyEqualFold(v string) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldEqualFold(FieldIdempotencyKey, v))
}

// IdempotencyKeyContainsFold applies the ContainsFold predicate on the "idempotency_key" field.
func IdempotencyKeyContainsFold(v string) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldContainsFold(FieldIdempotencyKey, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldLTE(FieldUserID, v))
}

// AnchorIDEQ applies the EQ predicate on the "anchor_id" field.
func AnchorIDEQ(v int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldEQ(FieldAnchorID, v))
}

// AnchorIDNEQ applies the NEQ predicate on the "anchor_id" field.
func AnchorIDNEQ(v int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldNEQ(FieldAnchorID, v))
}

// AnchorIDIn applies the In predicate on the "anchor_id" field.
func AnchorIDIn(vs ...int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldIn(FieldAnchorID, vs...))
}

// AnchorIDNotIn applies the NotIn predicate on the "anchor_id" field.
func AnchorIDNotIn(vs ...int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldNotIn(FieldAnchorID, vs...))
}

// AnchorIDGT applies the GT predicate on the "anchor_id" field.
func AnchorIDGT(v int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldGT(FieldAnchorID, v))
}

// AnchorIDGTE applies the GTE predicate on the "anchor_id" field.
func AnchorIDGTE(v int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldGTE(FieldAnchorID, v))
}

// AnchorIDLT applies the LT predicate on the "anchor_id" field.
func AnchorIDLT(v int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldLT(FieldAnchorID, v))
}

// AnchorIDLTE applies the LTE predicate on the "anchor_id" field.
func AnchorIDLTE(v int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldLTE(FieldAnchorID, v))
}

// RoomIDEQ applies the EQ predicate on the "room_id" field.
func RoomIDEQ(v int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldEQ(FieldRoomID, v))
}

// RoomIDNEQ applies the NEQ predicate on the "room_id" field.
func RoomIDNEQ(v int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldNEQ(FieldRoomID, v))
}

// RoomIDIn applies the In predicate on the "room_id" field.
func RoomIDIn(vs ...int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldIn(FieldRoomID, vs...))
}

// RoomIDNotIn applies the NotIn predicate on the "room_id" field.
func RoomIDNotIn(vs ...int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldNotIn(FieldRoomID, vs...))
}

// RoomIDGT applies the GT predicate on the "room_id" field.
func RoomIDGT(v int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldGT(FieldRoomID, v))
}

// RoomIDGTE applies the GTE predicate on the "room_id" field.
func RoomIDGTE(v int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldGTE(FieldRoomID, v))
}

// RoomIDLT applies the LT predicate on the "room_id" field.
func RoomIDLT(v int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldLT(FieldRoomID, v))
}

// RoomIDLTE applies the LTE predicate on the "room_id" field.
func RoomIDLTE(v int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldLTE(FieldRoomID, v))
}

// GiftIDEQ applies the EQ predicate on the "gift_id" field.
func GiftIDEQ(v int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldEQ(FieldGiftID, v))
}

// GiftIDNEQ applies the NEQ predicate on the "gift_id" field.
func GiftIDNEQ(v int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldNEQ(FieldGiftID, v))
}

// GiftIDIn applies the In predicate on the "gift_id" field.
func GiftIDIn(vs ...int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldIn(FieldGiftID, vs...))
}

// GiftIDNotIn applies the NotIn predicate on the "gift_id" field.
func GiftIDNotIn(vs ...int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldNotIn(FieldGiftID, vs...))
}

// GiftIDGT applies the GT predicate on the "gift_id" field.
func GiftIDGT(v int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldGT(FieldGiftID, v))
}

// GiftIDGTE applies the GTE predicate on the "gift_id" field.
func GiftIDGTE(v int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldGTE(FieldGiftID, v))
}

// GiftIDLT applies the LT predicate on the "gift_id" field.
func GiftIDLT(v int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldLT(FieldGiftID, v))
}

// GiftIDLTE applies the LTE predicate on the "gift_id" field.
func GiftIDLTE(v int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldLTE(FieldGiftID, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v int64) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldLTE(FieldAmount, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldNotIn(FieldStatus, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.GiftRecord {
	return predicate.GiftRecord(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GiftRecord) predicate.GiftRecord {
	return predicate.GiftRecord(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GiftRecord) predicate.GiftRecord {
	return predicate.GiftRecord(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GiftRecord) predicate.GiftRecord {
	return predicate.GiftRecord(sql.NotPredicates(p))
}
