// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: user/user_service.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_user_user_service_proto protoreflect.FileDescriptor

const file_user_user_service_proto_rawDesc = "" +
	"\n" +
	"\x17user/user_service.proto\x12\x04user\x1a\x13user/user_api.proto2\xb2\x01\n" +
	"\vUserService\x126\n" +
	"\aGetUser\x12\x14.user.GetUserRequest\x1a\x15.user.GetUserResponse\x129\n" +
	"\bRegister\x12\x15.user.RegisterRequest\x1a\x16.user.RegisterResponse\x120\n" +
	"\x05Login\x12\x12.user.LoginRequest\x1a\x13.user.LoginResponse2\xba\x01\n" +
	"\x18RoomAuthorizationService\x12N\n" +
	"\x0fGetUserRoomRole\x12\x1c.user.GetUserRoomRoleRequest\x1a\x1d.user.GetUserRoomRoleResponse\x12N\n" +
	"\x0fCheckPermission\x12\x1c.user.CheckPermissionRequest\x1a\x1d.user.CheckPermissionResponse2\xe0\x01\n" +
	"\fTokenService\x12H\n" +
	"\rValidateToken\x12\x1a.user.ValidateTokenRequest\x1a\x1b.user.ValidateTokenResponse\x12?\n" +
	"\n" +
	"ParseToken\x12\x17.user.ParseTokenRequest\x1a\x18.user.ParseTokenResponse\x12E\n" +
	"\fRefreshToken\x12\x19.user.RefreshTokenRequest\x1a\x1a.user.RefreshTokenResponseB\x18Z\x16shared/proto/user;userb\x06proto3"

var file_user_user_service_proto_goTypes = []any{
	(*GetUserRequest)(nil),          // 0: user.GetUserRequest
	(*RegisterRequest)(nil),         // 1: user.RegisterRequest
	(*LoginRequest)(nil),            // 2: user.LoginRequest
	(*GetUserRoomRoleRequest)(nil),  // 3: user.GetUserRoomRoleRequest
	(*CheckPermissionRequest)(nil),  // 4: user.CheckPermissionRequest
	(*ValidateTokenRequest)(nil),    // 5: user.ValidateTokenRequest
	(*ParseTokenRequest)(nil),       // 6: user.ParseTokenRequest
	(*RefreshTokenRequest)(nil),     // 7: user.RefreshTokenRequest
	(*GetUserResponse)(nil),         // 8: user.GetUserResponse
	(*RegisterResponse)(nil),        // 9: user.RegisterResponse
	(*LoginResponse)(nil),           // 10: user.LoginResponse
	(*GetUserRoomRoleResponse)(nil), // 11: user.GetUserRoomRoleResponse
	(*CheckPermissionResponse)(nil), // 12: user.CheckPermissionResponse
	(*ValidateTokenResponse)(nil),   // 13: user.ValidateTokenResponse
	(*ParseTokenResponse)(nil),      // 14: user.ParseTokenResponse
	(*RefreshTokenResponse)(nil),    // 15: user.RefreshTokenResponse
}
var file_user_user_service_proto_depIdxs = []int32{
	0,  // 0: user.UserService.GetUser:input_type -> user.GetUserRequest
	1,  // 1: user.UserService.Register:input_type -> user.RegisterRequest
	2,  // 2: user.UserService.Login:input_type -> user.LoginRequest
	3,  // 3: user.RoomAuthorizationService.GetUserRoomRole:input_type -> user.GetUserRoomRoleRequest
	4,  // 4: user.RoomAuthorizationService.CheckPermission:input_type -> user.CheckPermissionRequest
	5,  // 5: user.TokenService.ValidateToken:input_type -> user.ValidateTokenRequest
	6,  // 6: user.TokenService.ParseToken:input_type -> user.ParseTokenRequest
	7,  // 7: user.TokenService.RefreshToken:input_type -> user.RefreshTokenRequest
	8,  // 8: user.UserService.GetUser:output_type -> user.GetUserResponse
	9,  // 9: user.UserService.Register:output_type -> user.RegisterResponse
	10, // 10: user.UserService.Login:output_type -> user.LoginResponse
	11, // 11: user.RoomAuthorizationService.GetUserRoomRole:output_type -> user.GetUserRoomRoleResponse
	12, // 12: user.RoomAuthorizationService.CheckPermission:output_type -> user.CheckPermissionResponse
	13, // 13: user.TokenService.ValidateToken:output_type -> user.ValidateTokenResponse
	14, // 14: user.TokenService.ParseToken:output_type -> user.ParseTokenResponse
	15, // 15: user.TokenService.RefreshToken:output_type -> user.RefreshTokenResponse
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_user_user_service_proto_init() }
func file_user_user_service_proto_init() {
	if File_user_user_service_proto != nil {
		return
	}
	file_user_user_api_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_user_service_proto_rawDesc), len(file_user_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_user_user_service_proto_goTypes,
		DependencyIndexes: file_user_user_service_proto_depIdxs,
	}.Build()
	File_user_user_service_proto = out.File
	file_user_user_service_proto_goTypes = nil
	file_user_user_service_proto_depIdxs = nil
}
