// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Gift is the predicate function for gift builders.
type Gift func(*sql.Selector)

// Wallet is the predicate function for wallet builders.
type Wallet func(*sql.Selector)

// WalletTransaction is the predicate function for wallettransaction builders.
type WalletTransaction func(*sql.Selector)
